### ISSUE TITLE
Flaky test SamplingPercentageAdjustsAccordingToConstantHighProductionRate

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1037]
```
2018-12-28T22:39:32.2777167Z Starting test execution, please wait...
2018-12-28T22:40:23.4984741Z Failed   Microsoft.ApplicationInsights.WindowsServer.Channel.AdaptiveSamplingTelemetryProcessorTest.SamplingPercentageAdjustsAccordingToConstantHighProductionRate
2018-12-28T22:40:23.4985603Z Error Message:
2018-12-28T22:40:23.4985771Z  Assert.IsTrue failed. 
2018-12-28T22:40:23.4987663Z Stack Trace:
2018-12-28T22:40:23.4988582Z    at Microsoft.ApplicationInsights.WindowsServer.Channel.AdaptiveSamplingTelemetryProcessorTest.SamplingPercentageAdjustsAccordingToConstantHighProductionRate() in /mnt/a/1/s/Test/ServerTelemetryChannel.Test/Shared.Tests/AdaptiveSamplingTelemetryProcessorTest.cs:line 128
2018-12-28T22:40:23.4989225Z 
2018-12-28T22:40:23.4990530Z Standard Output Messages:
2018-12-28T22:40:23.4990780Z  
2018-12-28T22:40:23.4990970Z  
2018-12-28T22:40:23.4991151Z  Debug Trace:
2018-12-28T22:40:23.4992222Z  [Sampling% evaluation] 2018-12-28T22:39:59.4728938+00:00, Eps: 20, Current %: 100, New %: 25, Changed: False
2018-12-28T22:40:23.4992867Z  [Sampling% evaluation] 2018-12-28T22:40:00.4723852+00:00, Eps: 20.5, Current %: 100, New %: 20, Changed: False
2018-12-28T22:40:23.4993395Z  [Sampling% evaluation] 2018-12-28T22:40:01.4727203+00:00, Eps: 20.375, Current %: 100, New %: 20, Changed: True
2018-12-28T22:40:23.4993927Z  [Sampling% evaluation] 2018-12-28T22:40:02.4739779+00:00, Eps: 4, Current %: 20, New %: 25, Changed: False
2018-12-28T22:40:23.4994406Z  [Sampling% evaluation] 2018-12-28T22:40:03.4702612+00:00, Eps: 3.75, Current %: 20, New %: 25, Changed: False
2018-12-28T22:40:23.4994919Z  [Sampling% evaluation] 2018-12-28T22:40:04.4701655+00:00, Eps: 4.3125, Current %: 20, New %: 20, Changed: False
2018-12-28T22:40:23.4995400Z  [Sampling% evaluation] 2018-12-28T22:40:05.4708253+00:00, Eps: 4.734375, Current %: 20, New %: 20, Changed: False
2018-12-28T22:40:23.4995927Z  [Sampling% evaluation] 2018-12-28T22:40:06.4749983+00:00, Eps: 4.55078125, Current %: 20, New %: 20, Changed: False
2018-12-28T22:40:23.4996416Z  [Sampling% evaluation] 2018-12-28T22:40:07.4757375+00:00, Eps: 4.9130859375, Current %: 20, New %: 20, Changed: False
2018-12-28T22:40:23.4996954Z  [Sampling% evaluation] 2018-12-28T22:40:08.4715758+00:00, Eps: 4.434814453125, Current %: 20, New %: 20, Changed: False
2018-12-28T22:40:23.4997771Z  [Sampling% evaluation] 2018-12-28T22:40:09.4718122+00:00, Eps: 3.82611083984375, Current %: 20, New %: 25, Changed: True
2018-12-28T22:40:23.4998604Z  [Sampling% evaluation] 2018-12-28T22:40:10.4719975+00:00, Eps: 1, Current %: 25, New %: 100, Changed: False
2018-12-28T22:40:23.4999198Z  [Sampling% evaluation] 2018-12-28T22:40:11.4754562+00:00, Eps: 1.25, Current %: 25, New %: 100, Changed: True
2018-12-28T22:40:23.4999748Z  [Sampling% evaluation] 2018-12-28T22:40:12.4760677+00:00, Eps: 20, Current %: 100, New %: 25, Changed: False
2018-12-28T22:40:23.5000204Z  [Sampling% evaluation] 2018-12-28T22:40:13.4687556+00:00, Eps: 20, Current %: 100, New %: 25, Changed: False
2018-12-28T22:40:23.5000736Z  [Sampling% evaluation] 2018-12-28T22:40:14.4733533+00:00, Eps: 20, Current %: 100, New %: 25, Changed: True
2018-12-28T22:40:23.5001716Z  [Sampling% evaluation] 2018-12-28T22:40:15.4698518+00:00, Eps: 7, Current %: 25, New %: 16.6666666666667, Changed: False
2018-12-28T22:40:23.5002287Z  [Sampling% evaluation] 2018-12-28T22:40:16.4694474+00:00, Eps: 6, Current %: 25, New %: 20, Changed: False
2018-12-28T22:40:23.5002762Z  [Sampling% evaluation] 2018-12-28T22:40:17.4740224+00:00, Eps: 7, Current %: 25, New %: 16.6666666666667, Changed: True
2018-12-28T22:40:23.5003310Z  [Sampling% evaluation] 2018-12-28T22:40:18.4702060+00:00, Eps: 6, Current %: 16.6666666666667, New %: 12.5, Changed: False
2018-12-28T22:40:23.5003797Z  [Sampling% evaluation] 2018-12-28T22:40:19.4708565+00:00, Eps: 5, Current %: 16.6666666666667, New %: 16.6666666666667, Changed: False
2018-12-28T22:40:23.5004364Z  [Sampling% evaluation] 2018-12-28T22:40:20.4709985+00:00, Eps: 4.5, Current %: 16.6666666666667, New %: 16.6666666666667, Changed: False
2018-12-28T22:40:23.5004852Z  [Sampling% evaluation] 2018-12-28T22:40:21.4702893+00:00, Eps: 4.375, Current %: 16.6666666666667, New %: 16.6666666666667, Changed: False
2018-12-28T22:40:23.5005423Z  [Sampling% evaluation] 2018-12-28T22:40:22.4703054+00:00, Eps: 4.03125, Current %: 16.6666666666667, New %: 20, Changed: True
2018-12-28T22:40:23.5005872Z  [Sampling% evaluation] 2018-12-28T22:40:23.4702887+00:00, Eps: 4, Current %: 20, New %: 25, Changed: False
2018-12-28T22:40:23.5006317Z  'Ideal' telemetry item count: 125
2018-12-28T22:40:23.5006481Z  Expected range: from 63 to 187
2018-12-28T22:40:23.5006673Z  Actual telemetry item count: 201 (160.8% of ideal)
2018-12-28T22:40:23.5006781Z 
```

target: netstandard 2.0
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8087032

**Comment by lmolkova** [comment]
https://dev.azure.com/mseng/AppInsights/_build%2Fresults?buildId=8087258&_a=summary

```
2018-12-28T23:29:49.7856452Z Failed   SamplingPercentageAdjustsAccordingToConstantHighProductionRate
2018-12-28T23:29:49.7872204Z Error Message:
2018-12-28T23:29:49.7873333Z  Assert.IsTrue failed. 
2018-12-28T23:29:49.7874351Z Stack Trace:
2018-12-28T23:29:49.7874571Z    at Microsoft.ApplicationInsights.WindowsServer.Channel.AdaptiveSamplingTelemetryProcessorTest.SamplingPercentageAdjustsAccordingToConstantHighProductionRate() in E:\A\_work\426\s\Test\ServerTelemetryChannel.Test\Shared.Tests\AdaptiveSamplingTelemetryProcessorTest.cs:line 127
2018-12-28T23:29:49.7874706Z 
2018-12-28T23:29:49.7889336Z Standard Output Messages:
2018-12-28T23:29:49.7891026Z  
2018-12-28T23:29:49.7891211Z 
2018-12-28T23:29:49.7891276Z Debug Trace:
2018-12-28T23:29:49.7891395Z [Sampling% evaluation] 2018-12-28T23:29:25.7477883+00:00, Eps: 22, Current %: 100, New %: 20, Changed: False
2018-12-28T23:29:49.7891794Z  [Sampling% evaluation] 2018-12-28T23:29:26.7460730+00:00, Eps: 21.25, Current %: 100, New %: 20, Changed: True
2018-12-28T23:29:49.7891894Z  [Sampling% evaluation] 2018-12-28T23:29:27.7453113+00:00, Eps: 2, Current %: 20, New %: 50, Changed: False
2018-12-28T23:29:49.7892010Z  [Sampling% evaluation] 2018-12-28T23:29:28.7487080+00:00, Eps: 2, Current %: 20, New %: 50, Changed: True
2018-12-28T23:29:49.7892373Z  [Sampling% evaluation] 2018-12-28T23:29:29.7459247+00:00, Eps: 13, Current %: 50, New %: 16.6666666666667, Changed: False
2018-12-28T23:29:49.7892616Z  [Sampling% evaluation] 2018-12-28T23:29:30.7449793+00:00, Eps: 11.75, Current %: 50, New %: 20, Changed: False
2018-12-28T23:29:49.7892712Z  [Sampling% evaluation] 2018-12-28T23:29:31.7462804+00:00, Eps: 11.3125, Current %: 50, New %: 20, Changed: True
2018-12-28T23:29:49.7892829Z  [Sampling% evaluation] 2018-12-28T23:29:32.7495773+00:00, Eps: 6, Current %: 20, New %: 16.6666666666667, Changed: False
2018-12-28T23:29:49.7892922Z  [Sampling% evaluation] 2018-12-28T23:29:33.7435527+00:00, Eps: 6, Current %: 20, New %: 16.6666666666667, Changed: False
2018-12-28T23:29:49.7893036Z  [Sampling% evaluation] 2018-12-28T23:29:34.7467852+00:00, Eps: 5.25, Current %: 20, New %: 16.6666666666667, Changed: True
2018-12-28T23:29:49.7893135Z  [Sampling% evaluation] 2018-12-28T23:29:35.7467522+00:00, Eps: 5, Current %: 16.6666666666667, New %: 16.6666666666667, Changed: False
2018-12-28T23:29:49.7893264Z  [Sampling% evaluation] 2018-12-28T23:29:36.7445709+00:00, Eps: 4.25, Current %: 16.6666666666667, New %: 16.6666666666667, Changed: False
2018-12-28T23:29:49.7893397Z  [Sampling% evaluation] 2018-12-28T23:29:37.7493634+00:00, Eps: 3.9375, Current %: 16.6666666666667, New %: 20, Changed: True
2018-12-28T23:29:49.7893509Z  [Sampling% evaluation] 2018-12-28T23:29:38.7495851+00:00, Eps: 7, Current %: 20, New %: 14.2857142857143, Changed: False
2018-12-28T23:29:49.7893602Z  [Sampling% evaluation] 2018-12-28T23:29:39.7439449+00:00, Eps: 6, Current %: 20, New %: 16.6666666666667, Changed: False
2018-12-28T23:29:49.7893714Z  [Sampling% evaluation] 2018-12-28T23:29:40.7467817+00:00, Eps: 6.75, Current %: 20, New %: 14.2857142857143, Changed: True
2018-12-28T23:29:49.7893808Z  [Sampling% evaluation] 2018-12-28T23:29:41.7472640+00:00, Eps: 0, Current %: 14.2857142857143, New %: 100, Changed: False
2018-12-28T23:29:49.7893927Z  [Sampling% evaluation] 2018-12-28T23:29:42.7443445+00:00, Eps: 0, Current %: 14.2857142857143, New %: 100, Changed: False
2018-12-28T23:29:49.7894029Z  [Sampling% evaluation] 2018-12-28T23:29:43.7463852+00:00, Eps: 0.25, Current %: 14.2857142857143, New %: 100, Changed: True
2018-12-28T23:29:49.7894120Z  [Sampling% evaluation] 2018-12-28T23:29:44.7480193+00:00, Eps: 18, Current %: 100, New %: 25, Changed: False
2018-12-28T23:29:49.7894227Z  [Sampling% evaluation] 2018-12-28T23:29:45.7442396+00:00, Eps: 18.5, Current %: 100, New %: 25, Changed: False
2018-12-28T23:29:49.7894317Z  [Sampling% evaluation] 2018-12-28T23:29:46.7475256+00:00, Eps: 19.125, Current %: 100, New %: 25, Changed: True
2018-12-28T23:29:49.7894425Z  [Sampling% evaluation] 2018-12-28T23:29:47.7474951+00:00, Eps: 1, Current %: 25, New %: 100, Changed: False
2018-12-28T23:29:49.7894513Z  [Sampling% evaluation] 2018-12-28T23:29:48.7447141+00:00, Eps: 1.75, Current %: 25, New %: 50, Changed: False
2018-12-28T23:29:49.7894616Z  'Ideal' telemetry item count: 125
2018-12-28T23:29:49.7894679Z  Expected range: from 63 to 187
2018-12-28T23:29:49.7894902Z  Actual telemetry item count: 190 (152% of ideal)
```

**Comment by lmolkova** [comment]
another one 

```
2018-12-29T00:54:17.0674408Z Failed   Microsoft.ApplicationInsights.WindowsServer.Channel.AdaptiveSamplingTelemetryProcessorTest.SamplingPercentageAdjustsAccordingToConstantHighProductionRate
2018-12-29T00:54:17.0675316Z Error Message:
2018-12-29T00:54:17.0675619Z  Assert.IsTrue failed. 
2018-12-29T00:54:17.0675768Z Stack Trace:
2018-12-29T00:54:17.0676014Z    at Microsoft.ApplicationInsights.WindowsServer.Channel.AdaptiveSamplingTelemetryProcessorTest.SamplingPercentageAdjustsAccordingToConstantHighProductionRate() in /mnt/a/1/s/Test/ServerTelemetryChannel.Test/Shared.Tests/AdaptiveSamplingTelemetryProcessorTest.cs:line 128
2018-12-29T00:54:17.0676179Z 
2018-12-29T00:54:17.0676500Z Standard Output Messages:
2018-12-29T00:54:17.0676685Z  
2018-12-29T00:54:17.0677073Z  
2018-12-29T00:54:17.0695033Z  Debug Trace:
2018-12-29T00:54:17.0696632Z  [Sampling% evaluation] 2018-12-29T00:53:53.0431593+00:00, Eps: 22, Current %: 100, New %: 20, Changed: False
2018-12-29T00:54:17.0698139Z  [Sampling% evaluation] 2018-12-29T00:53:54.0439926+00:00, Eps: 21.5, Current %: 100, New %: 20, Changed: True
2018-12-29T00:54:17.0698804Z  [Sampling% evaluation] 2018-12-29T00:53:55.0424045+00:00, Eps: 4, Current %: 20, New %: 25, Changed: False
2018-12-29T00:54:17.0699355Z  [Sampling% evaluation] 2018-12-29T00:53:56.0408001+00:00, Eps: 4.5, Current %: 20, New %: 20, Changed: False
2018-12-29T00:54:17.0699944Z  [Sampling% evaluation] 2018-12-29T00:53:57.0418306+00:00, Eps: 4.625, Current %: 20, New %: 20, Changed: False
2018-12-29T00:54:17.0705736Z  [Sampling% evaluation] 2018-12-29T00:53:58.0390096+00:00, Eps: 4.21875, Current %: 20, New %: 20, Changed: False
2018-12-29T00:54:17.0706532Z  [Sampling% evaluation] 2018-12-29T00:53:59.0431897+00:00, Eps: 3.6640625, Current %: 20, New %: 25, Changed: True
2018-12-29T00:54:17.0707223Z  [Sampling% evaluation] 2018-12-29T00:54:00.0448009+00:00, Eps: 3, Current %: 25, New %: 33.3333333333333, Changed: False
2018-12-29T00:54:17.0707802Z  [Sampling% evaluation] 2018-12-29T00:54:01.0424513+00:00, Eps: 3.5, Current %: 25, New %: 33.3333333333333, Changed: False
2018-12-29T00:54:17.0708355Z  [Sampling% evaluation] 2018-12-29T00:54:02.0427816+00:00, Eps: 4.625, Current %: 25, New %: 25, Changed: False
2018-12-29T00:54:17.0709089Z  [Sampling% evaluation] 2018-12-29T00:54:03.0394652+00:00, Eps: 4.46875, Current %: 25, New %: 25, Changed: False
2018-12-29T00:54:17.0709734Z  [Sampling% evaluation] 2018-12-29T00:54:04.0441759+00:00, Eps: 4.6015625, Current %: 25, New %: 25, Changed: False
2018-12-29T00:54:17.0710302Z  [Sampling% evaluation] 2018-12-29T00:54:05.0411709+00:00, Eps: 4.451171875, Current %: 25, New %: 25, Changed: False
2018-12-29T00:54:17.0710879Z  [Sampling% evaluation] 2018-12-29T00:54:06.0385874+00:00, Eps: 4.33837890625, Current %: 25, New %: 25, Changed: False
2018-12-29T00:54:17.0711384Z  [Sampling% evaluation] 2018-12-29T00:54:07.0439372+00:00, Eps: 5.2537841796875, Current %: 25, New %: 20, Changed: True
2018-12-29T00:54:17.0711948Z  [Sampling% evaluation] 2018-12-29T00:54:08.0419896+00:00, Eps: 4, Current %: 20, New %: 25, Changed: False
2018-12-29T00:54:17.0712440Z  [Sampling% evaluation] 2018-12-29T00:54:09.0476609+00:00, Eps: 3.75, Current %: 20, New %: 25, Changed: True
2018-12-29T00:54:17.0713060Z  [Sampling% evaluation] 2018-12-29T00:54:10.0392786+00:00, Eps: 7, Current %: 25, New %: 16.6666666666667, Changed: False
2018-12-29T00:54:17.0713932Z  [Sampling% evaluation] 2018-12-29T00:54:11.0398399+00:00, Eps: 6.5, Current %: 25, New %: 16.6666666666667, Changed: False
2018-12-29T00:54:17.0714648Z  [Sampling% evaluation] 2018-12-29T00:54:12.0389691+00:00, Eps: 5.375, Current %: 25, New %: 20, Changed: True
2018-12-29T00:54:17.0715148Z  [Sampling% evaluation] 2018-12-29T00:54:13.0393846+00:00, Eps: 0, Current %: 20, New %: 100, Changed: False
2018-12-29T00:54:17.0715727Z  [Sampling% evaluation] 2018-12-29T00:54:14.0443760+00:00, Eps: 0.75, Current %: 20, New %: 100, Changed: True
2018-12-29T00:54:17.0716371Z  [Sampling% evaluation] 2018-12-29T00:54:15.0405226+00:00, Eps: 20, Current %: 100, New %: 25, Changed: False
2018-12-29T00:54:17.0716996Z  [Sampling% evaluation] 2018-12-29T00:54:16.0403368+00:00, Eps: 20, Current %: 100, New %: 25, Changed: False
2018-12-29T00:54:17.0717486Z  [Sampling% evaluation] 2018-12-29T00:54:17.0416971+00:00, Eps: 20, Current %: 100, New %: 25, Changed: True
2018-12-29T00:54:17.0717945Z  'Ideal' telemetry item count: 125
2018-12-29T00:54:17.0718169Z  Expected range: from 63 to 187
2018-12-29T00:54:17.0718371Z  Actual telemetry item count: 187 (149.6% of ideal)
```

https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8087719

target: netstandard 2.0

**Comment by TimothyMothra** [comment]
moved to other issue
