### ISSUE TITLE
Flaky test WhenSendIsCalledTheEventIsBeingQueuedInTheBuffer

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1039]
```
2018-12-28T23:02:28.2750225Z Starting test execution, please wait...
2018-12-28T23:02:52.4362360Z Failed   Microsoft.ApplicationInsights.Channel.InMemoryChannelTest.WhenSendIsCalledTheEventIsBeingQueuedInTheBuffer
2018-12-28T23:02:53.2766762Z Error Message:
2018-12-28T23:02:53.2767745Z  Test method Microsoft.ApplicationInsights.Channel.InMemoryChannelTest.WhenSendIsCalledTheEventIsBeingQueuedInTheBuffer threw exception: 
2018-12-28T23:02:53.2768212Z System.ArgumentNullException: Value cannot be null.
2018-12-28T23:02:53.2768524Z Parameter name: source
2018-12-28T23:02:53.2768856Z Stack Trace:
2018-12-28T23:02:53.2769169Z     at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
2018-12-28T23:02:53.2769537Z    at Microsoft.ApplicationInsights.Channel.InMemoryChannelTest.WhenSendIsCalledTheEventIsBeingQueuedInTheBuffer() in /mnt/a/1/s/Test/Microsoft.ApplicationInsights.Test/Shared/Channel/InMemoryChannelTest.cs:line 28
2018-12-28T23:02:53.2769847Z 
2018-12-28T23:02:57.2755465Z Results File: /mnt/a/1/s/Test/Microsoft.ApplicationInsights.Test/netcoreapp11/TestResults/_fv-az441_2018-12-28_23:02:29.trx
2018-12-28T23:02:57.2755971Z 
```

target: netstandard 1.1

https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8087135

**Comment by TimothyMothra** [comment]
I'm no longer seeing this test fail, so i'm closing this task.
