### ISSUE TITLE
Flaky test PerformanceCounterTelemetryDeepCloneCopiesAllProperties

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1043]
```
2018-12-29T00:23:18.9695986Z Failed   PerformanceCounterTelemetryDeepCloneCopiesAllProperties
2018-12-29T00:23:18.9713750Z Error Message:
2018-12-29T00:23:18.9714101Z  Assert.IsTrue failed. 
2018-12-29T00:23:18.9714376Z Begin Differences (1 differences):
2018-12-29T00:23:18.9714711Z Types [String,String], Item Expected.Context.Properties.Key != Actual.Context.Properties.Key, Values (p1,CounterInstanceName)
2018-12-29T00:23:18.9714838Z End Differences (Maximum of 1 differences shown).
2018-12-29T00:23:18.9715087Z Stack Trace:
2018-12-29T00:23:18.9715201Z    at Microsoft.ApplicationInsights.DataContracts.PerformanceCounterTelemetryTest.PerformanceCounterTelemetryDeepCloneCopiesAllProperties() in E:\A\_work\426\s\Test\Microsoft.ApplicationInsights.Test\Shared\DataContracts\PerformanceCounterTelemetryTest.cs:line 51
2018-12-29T00:23:18.9715315Z 
```

target: netstandard 1.1
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8087533

**Comment by lmolkova** [comment]
```
2018-12-29T00:34:59.4464511Z Failed   Microsoft.ApplicationInsights.DataContracts.PerformanceCounterTelemetryTest.PerformanceCounterTelemetryDeepCloneCopiesAllProperties
2018-12-29T00:34:59.4474682Z Error Message:
2018-12-29T00:34:59.4488610Z  Assert.IsTrue failed. 
2018-12-29T00:34:59.4489199Z Begin Differences (1 differences):
2018-12-29T00:34:59.4489577Z Types [String,String], Item Expected.Context.Properties.Key != Actual.Context.Properties.Key, Values (p1,CounterInstanceName)
2018-12-29T00:34:59.4489982Z End Differences (Maximum of 1 differences shown).
2018-12-29T00:34:59.4490308Z Stack Trace:
2018-12-29T00:34:59.4490782Z    at Microsoft.ApplicationInsights.DataContracts.PerformanceCounterTelemetryTest.PerformanceCounterTelemetryDeepCloneCopiesAllProperties() in /mnt/a/1/s/Test/Microsoft.ApplicationInsights.Test/Shared/DataContracts/PerformanceCounterTelemetryTest.cs:line 52
2018-12-29T00:34:59.4491107Z 
```

target: netstandard 1.1
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8087627

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
