### ISSUE TITLE
MethodsAreImplementedConsistentlyWithTheirAttributes does not test applicaiton name correctly and fails on .netcoreapp2.0 

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet#1128]
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=9392652&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b

```
Starting test execution, please wait...
Failed   MethodsAreImplementedConsistentlyWithTheirAttributes
Error Message:
 Test method Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSourceTest.MethodsAreImplementedConsistentlyWithTheirAttributes threw exception: 
System.Exception: OperationIsNullWarning is implemented incorrectly: Application Name. expected: '', actual: 'testhost' ---> System.Exception: Application Name. expected: '', actual: 'testhost'
Stack Trace:
    at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.AssertEqual[T](T expected, T actual, String message) in E:\A\_work\538\s\Test\TestFramework\Shared\EventSourceTest.cs:line 115
   at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.VerifyMethodImplementation(EventSource eventSource, MethodInfo eventMethod) in E:\A\_work\538\s\Test\TestFramework\Shared\EventSourceTest.cs:line 37
--- End of inner exception stack trace ---
    at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.VerifyMethodImplementation(EventSource eventSource, MethodInfo eventMethod) in E:\A\_work\538\s\Test\TestFramework\Shared\EventSourceTest.cs:line 41
   at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.MethodsAreImplementedConsistentlyWithTheirAttributes(EventSource eventSource) in E:\A\_work\538\s\Test\TestFramework\Shared\EventSourceTest.cs:line 16
```

This happens because tests set `expectedApplicationName` to empty string for all .net core.
```csharp
#if !NETCOREAPP
            string expectedApplicationName = AppDomain.CurrentDomain.FriendlyName;
#else
            string expectedApplicationName = "";
#endif
            string actualApplicationName = actualEvent.Payload.Last().ToString();
            AssertEqual(expectedApplicationName, actualApplicationName, "Application Name");
```

the obvious fix to use `AppDomain.CurrentDomain.FriendlyName` on netcoreapp2.0., but it leads to another failure 

```

Failed   MethodsAreImplementedConsistentlyWithTheirAttributes
Error Message:
 Test method Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.WebEventSourceTest.MethodsAreImplementedConsistentlyWithTheirAttributes threw exception: 
System.Exception: BackoffDisabled is implemented incorrectly: Application Name. expected: 'testhost', actual: '' ---> System.Exception: Application Name. expected: 'testhost', actual: ''
Stack Trace:
    at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.AssertEqual[T](T expected, T actual, String message) in E:\A\_work\228\s\Test\TestFramework\Shared\EventSourceTest.cs:line 115
   at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.VerifyMethodImplementation(EventSource eventSource, MethodInfo eventMethod) in E:\A\_work\228\s\Test\TestFramework\Shared\EventSourceTest.cs:line 37
--- End of inner exception stack trace ---
    at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.VerifyMethodImplementation(EventSource eventSource, MethodInfo eventMethod) in E:\A\_work\228\s\Test\TestFramework\Shared\EventSourceTest.cs:line 41
   at Microsoft.ApplicationInsights.TestFramework.EventSourceTest.MethodsAreImplementedConsistentlyWithTheirAttributes(EventSource eventSource) in E:\A\_work\228\s\Test\TestFramework\Shared\EventSourceTest.cs:line 16
```

which seems to be caused by some race-condition, or some other unexpected behavior that is fixed with something like https://github.com/Microsoft/ApplicationInsights-dotnet/commit/0a2c4e0dafdb41204c7619f3b50db19657f9cb73#diff-38c3bb17d4df474170d2d57acf211a18R13 but the root cause is unknown.

This issue does **not** reproduce locally - only on the build machine

**Comment by lmolkova** [comment]
does not repro anymore after #1125
