### ISSUE TITLE
Internal exception when initializing

### ISSUE THREAD

**Issue by jorismathijssen** [microsoft/ApplicationInsights-dotnet#1162]
## Repro Steps
We have Microsoft.ApplicationInsights.AspNetCore 2.7.1 installed and somehow in our logging we are receiving the error below in our logging. I have read a few posts about this issue but all those post are related to the Microsoft.ApplicationInsight 2.8.x build in combination with azureFunctions. But we don't use both of them.

Could this be an error in my code or is it an internal problem?

##  Actual Behavior
`AI (Internal): [Microsoft-ApplicationInsights-Core] [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer, exception message - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Cookies()
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.UpdateRequestTelemetryFromPlatformContext(RequestTelemetry requestTelemetry, HttpContext platformContext)
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.OnInitializeTelemetry(HttpContext platformContext, RequestTelemetry requestTelemetry, ITelemetry telemetry)
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.TelemetryInitializerBase.Initialize(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]`

## Expected Behavior
We don't want this error flooding our Microsoft.ApplicationInsight logging.

## Version Info 
SDK Version : 2.7.1
.NET Version :	.net Core 2.2.5						
How Application was onboarded with SDK(VisualStudio) :
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) :
IIS

**Comment by jorismathijssen** [comment]
I just realized that i posted this on the wrong repository... Is this a problem?
