### ISSUE TITLE
The type initializer for 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' threw an exception.

### ISSUE THREAD

**Issue by Alxandr** [microsoft/ApplicationInsights-dotnet#1223]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Add `ApplicationInsights` package to the project.
2. Use `TelemetryConfiguration`.

Note; this is likely related to the actual project (I don't believe something like this would slip through if not). I'm trying to use this in an Azure Function project, but I'm unfortunately unable to produce a reduced example.

##  Actual Behavior

During application startup I get the following exception:

```
System.TypeInitializationException: The type initializer for 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' threw an exception. ---> System.MissingMethodException: Method not found: 'Boolean System.Diagnostics.Activity.get_ForceDefaultIdFormat()'.
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.<>c.<.cctor>b__11_0()
   at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.CreateDefault()
   at Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions..ctor(IEnumerable`1 configureOptions)
   at lambda_method(Closure , IResolverContext )
   at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6596
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7840
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7825
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6595
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6555
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.WrappersSupport.GetArrayExpression(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 2894
   at DryIoc.ExpressionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7690
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6625
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 210
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 101
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetRequiredService(Type serviceType) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 84
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(Boolean skipHostStartup, Boolean skipHostConfigurationParsing) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DefaultScriptHostBuilder.cs:line 59
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.BuildHost(Boolean skipHostStartup, Boolean skipHostJsonConfiguration) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 397
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(CancellationToken cancellationToken, Int32 attemptCount, JobHostStartupMode startupMode) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 188
```

## Expected Behavior

It should not throw an exception.

## Version Info 
Microsoft.ApplicationInsights : 2.11.0
Microsoft.ApplicationInsights.AspNetCore : 2.8.0
Microsoft.NET.Sdk.Functions : 1.0.29
SDK Version : .NET Core SDK 3.0.100
.NET Version : .NET Core 2.2
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Nuget Package
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Running locally, from visual studio using F5,

**Comment by TimothyMothra** [comment]
The exception is `System.MissingMethodException` referring to `Activity.ForceDefaultIdFormat`.

Here's the constructor referenced in that call stack:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/69639b40a38ca5f7e79639a3da42c30db2291ea6/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L57-L67

Looks like this was added recently: https://github.com/microsoft/ApplicationInsights-dotnet/pull/1201


This compiles, which would suggest that the method does indeed exist.
@lmolkova, could there be a version mismatch with what Functions are using?

https://github.com/microsoft/ApplicationInsights-dotnet/blob/69639b40a38ca5f7e79639a3da42c30db2291ea6/src/Microsoft.ApplicationInsights/Microsoft.ApplicationInsights.csproj#L48

**Comment by Alxandr** [comment]
@TimothyMothra I did some more digging. `Assembly.Load("System.Diagnostics.DiagnosticSource")` gives me `4.0.something` (going off memory here, left work a few hours ago). The location was part of the function host though.

**Comment by lmolkova** [comment]
@Alxandr  can you check that your binding redirects use latest DiagnosticSource package? 4.0.4.* eems like you use old diagnostic source

**Comment by Alxandr** [comment]
Not sure you can do binding redirects on azure functions, as you don't own the host? Nor where you'd find them. The issue is that azure functions bundles their own diagnosticsource, which as far as I know is already loaded by the time it runs any app code (where I call app insights).

**Comment by lmolkova** [comment]
yes, azure functions still depend on older diagnosticsource. For now, you cannot update ApplicationInsights in functions, we are working on updating version in Functions to solve this issue.

**Comment by Alxandr** [comment]
Do you know which version of appinsights will work in functions?

**Comment by lmolkova** [comment]
2.10 should work fine.

**Comment by aedwill** [comment]
Remember DLL hell?  Seems now it's Azure NuGet Version Hell.

**Comment by nianton** [comment]
I had the same problem with latest Azure Functions runtime v2.0.12742.0 and the latest Microsoft.ApplicationsInsights nuget (v2.11). I downgraded to v2.10 of Microsft.ApplicationInsights package and seems to be working fine.

**Comment by tedterrill** [comment]
I have some function apps that I still need to run at version 1 because of .NET framework dependencies. This exception suddenly popped up the other day. Downgrading to v2.10 of Microsoft.ApplicationInsights worked for us.
