### ISSUE TITLE
Nuget Package install failed to add ApplicationInsights.config

### ISSUE THREAD

**Issue by LukeRH** [microsoft/ApplicationInsights-dotnet#1337]
Hi,
When i try to add app insights using the rhm option on a asp.net project i get the following error
Could not add Application Insights to project.

The nuget package install failed to add the ApplicationInsights.config

![image](https://user-images.githubusercontent.com/17493218/70129092-0b508600-1676-11ea-99e6-07c23970045a.png)

I have tried adding app insights to a brand new asp.net project and it works. Is there a log location which might provide more information about what is going wrong. I have checked VS output and event viewer.

Please could someone help?

Thanks
Luke

**Comment by cijothomas** [comment]
@TimothyMothra can you help?

**Comment by TimothyMothra** [comment]
@LukeRH what is the "rhm option"? Sorry, I'm not familiar with this name.

Can you please share the **name** and **version** of the specific package? This will help me 

Addressing your question about logs, it's the nuget.exe that installs a package. You can try to install the package via command line and you might get more logs. I would be curious to see these logs myself.

**Comment by LukeRH** [comment]
Apologies i mean right hand mouse on the project in visual studio then add then application insights as prescribed by the documentation (https://docs.microsoft.com/en-us/azure/azure-monitor/learn/quick-monitor-portal). 

I tried installing using the package Microsoft.ApplicationInsights.Web (not sure if that is the correct one or not). It successfully adds the package but does not add files such as ApplicationInsights.config that the wizard does. I assume this is part of the app insights wizard functionality.

**Comment by LukeRH** [comment]
PM> Install-Package Microsoft.ApplicationInsights.Web -ProjectName SPFServer
Restoring packages for C:\Repos\SDX\SPF\Server Projects\SPFServer\SPFServer.vbproj...
NU1608: Detected package version outside of dependency constraint: NEST 1.7.2 requires Newtonsoft.Json (>= 7.0.0 && < 9.0.0) but version Newtonsoft.Json 12.0.2 was resolved.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Repos\SDX\SPF\Server Projects\SPFServer\obj\project.assets.json
Restore completed in 144.61 ms for C:\Repos\SDX\SPF\Server Projects\SPFServer\SPFServer.vbproj.
NU1603: EnterpriseLibrary.Logging 6.0.1304 depends on EnterpriseLibrary.Common (>= 6.0.0) but EnterpriseLibrary.Common 6.0.0 was not found. An approximate best match of EnterpriseLibrary.Common 6.0.1304 was resolved.
NU1608: Detected package version outside of dependency constraint: NEST 1.7.2 requires Newtonsoft.Json (>= 7.0.0 && < 9.0.0) but version Newtonsoft.Json 12.0.2 was resolved.
NU1608: Detected package version outside of dependency constraint: NEST 1.7.2 requires Newtonsoft.Json (>= 7.0.0 && < 9.0.0) but version Newtonsoft.Json 12.0.2 was resolved.
NU1603: EnterpriseLibrary.Logging 6.0.1304 depends on EnterpriseLibrary.Common (>= 6.0.0) but EnterpriseLibrary.Common 6.0.0 was not found. An approximate best match of EnterpriseLibrary.Common 6.0.1304 was resolved.
NU1608: Detected package version outside of dependency constraint: NEST 1.7.2 requires Newtonsoft.Json (>= 7.0.0 && < 9.0.0) but version Newtonsoft.Json 12.0.2 was resolved.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Repos\SDX\SPF\Services\Intergraph.SPF.Server.API.IntegrationTests.SDADB\obj\project.assets.json
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Repos\SDX\SPF\Services\Intergraph.SPF.Server.API.ClientSupport.UnitTests\obj\project.assets.json
Restore completed in 33.02 ms for C:\Repos\SDX\SPF\Services\Intergraph.SPF.Server.API.IntegrationTests.SDADB\Intergraph.SPF.Server.API.IntegrationTests.SDADB.csproj.
Committing restore...
Restore completed in 12.23 ms for C:\Repos\SDX\SPF\Services\Intergraph.SPF.Server.API.ClientSupport.UnitTests\Intergraph.SPF.Server.API.ClientSupport.UnitTests.csproj.
Assets file has not changed. Skipping assets file writing. Path: C:\Repos\SDX\SPF\Services\Intergraph.SPF.Server.API.ClientSupport.IntegrationTests\obj\project.assets.json
Restore completed in 33.06 ms for C:\Repos\SDX\SPF\Services\Intergraph.SPF.Server.API.ClientSupport.IntegrationTests\Intergraph.SPF.Server.API.ClientSupport.IntegrationTests.csproj.

NuGet Config files used:
    C:\Users\lhiscock\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
Executing nuget actions took 11.97 sec
Time Elapsed: 00:00:31.3282429

**Comment by TimothyMothra** [comment]
Hey @LukeRH, 
You're correct, that's the right package to use. 

Can you please run the same command with the `-Verbose` flag?
I just tested that locally and confirmed that it reports if it was able to copy the config file. I'm hoping this will catch what error happening in your case.

**Comment by LukeRH** [comment]
[nuget.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/3939432/nuget.txt)
Hi, 
I have attached the verbose logs, i do not see reference to the ApplicationInsights.config from within them.

Thanks
Luke

**Comment by kfertitta** [comment]
Was there ever a resolution to this?  I'm hitting the exact same problem.

Thanks in advance.

**Comment by TimothyMothra** [comment]
Hi @kfertitta, we were never able to repro this case.
When I install with Verbose logs I was able to see the config file.

If you can collect and share your logs that would be helpful.

**Comment by kfertitta** [comment]
@TimothyMothra Thanks much for the prompt reply.  Eager to get this sorted.  Please find attached the verbose log output.


[log.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/4483219/log.txt)

**Comment by TimothyMothra** [comment]
I created an empty project and ran the command `Install-Package Microsoft.ApplicationInsights.Web -Verbose`
My [verbose log](https://github.com/microsoft/ApplicationInsights-dotnet/files/4483739/install-package.verbose.log) includes this line: 
> Added file 'ApplicationInsights.config' to project 'WebApplication28'.

I don't see this line in either of the other attached log files and I don't know what would cause this.

**Comment by kfertitta** [comment]
I updated to 16.5.4 from 16.5.2, but that didn't make a difference.  I also am able to run the AppInsights wizard from a freshly generated project and it works just fine -- completes and installs the `ApplicationInsights.config` file.

Not sure where to go from here.  Is there a semi-manual process?  If I look at what was added to my test from-scratch project, it's a LOT of stuff -- particularly in the web.config.  Not certain if trying to add telemetry support manually is a viable path.

**Comment by TimothyMothra** [comment]
@kfertitta just out of curiosity, what version of Nuget Package Manager is your Visual Studio using? (Help > About > Installed Products)

We normally wouldn't recommend doing these changes manually because as you identified, it's A LOT!
In the interest of getting you unblocked, the best recommendation I can give would be to start an empty project and copy those changes (web.config and applicationinsights.config) to your intended project.

I have examples of default config files here: https://github.com/microsoft/ApplicationInsights-Home/tree/master/Samples/.NET%20Config%20File
There haven't been any changes since the 2.10 version, but if you want a more recent example ping me here and I'll get that updated.

**Comment by kfertitta** [comment]
Thanks @TimothyMothra .  I see version 5.5.0 of the NuGet Package Manager after today's update to 16.5.4.

And, I appreciate the advice on going ahead with manual mods -- if it's only the `web.config` and `applicationinsights.config` (and, of course, the `.csproj`) then we can deal with it.  

I did perform a WinMerge diff of the entire folder structure of a from-scratch, single-page ASP.NET Web App (not ASP.NET Core, notably).  If that's the best approach, I'll charge ahead, barring any revelations you uncover, cuz we are very much blocked and this app has a lot of new functionality that we definitely need to monitor.

**Comment by DamianResler** [comment]
@TimothyMothra I have this same issue, and no trace of applicationinsights.config in verbose logs eather.

**Comment by TimothyMothra** [comment]
I've had some internal customers contact me this week about this.
We haven't been able to reproduce this and are still looking for details.
If someone can create a small repro app that would be very valuable!

@kfertitta, @DamianResler can you please share which framework versions you're using in your projects?

**Comment by kfertitta** [comment]
We're using 4.7.1.  Wish we could get you a small repo, but we see it only in our real website, which is obviously too large to be useful to you.

**Comment by TimothyMothra** [comment]
I've opened an issue against NuGet asking for help getting detailed logs. https://github.com/NuGet/Home/issues/9448

Their issue template asks that we run this command: (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag)

When I get time I will test this in a new app and share what I expect the logs to look like.

**Comment by DamianResler** [comment]
I'm using 4.6.2. But what is intresting, Oddly, it works fine on a newly created project

**Comment by kfertitta** [comment]
Yes, works on a new project for me as well.  I was able to look at the diffs performed on a new project and manually apply them to mine and it all seems to work -- both when run locally and when running in Azure.  I just comment out the `InstrumentationKey` in the `Application.config` file so that local runs don't pollute the Azure resource with data from local runs.

**Comment by TimothyMothra** [comment]
@DamianResler, @kfertitta Are your projects using the newer NetCore/ProjectReference csproj format?
I got a response from the NuGet team that our install files are not supported by these types of projects.

This is expected because if you are using the newer NetCore project, you do not need an applicationinsights.config or a web.config.
There will be a Startup.cs class where you can add our SDK and an appsettings.json that you can use to configure:
```
    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        // The following line enables Application Insights telemetry collection.
        services.AddApplicationInsightsTelemetry();

        // This code adds other services for your application.
        services.AddMvc();
    }
```
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio


Please let me know if this applies to you!

**Comment by kfertitta** [comment]
@TimothyMothra Thanks very much for sticking with us through this.  No, I'm not using the new SDK-style projects (though I'd very much like to be).  We've not yet migrated this somewhat legacy conventional ASP.NET project.  

However, we ARE using `<PackageReference>` and not `packages.config`.  That's valid nowadays for .NET Framework non-SDK-style apps, but perhaps it's throwing off this particular package?

**Comment by TimothyMothra** [comment]
My understanding is that PackageReference will install packages differently and it ignores our older format of installs.

I haven't seen a net framework web project converted to use PackageReference.
It sounds like you've done this: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

My concern is that this may not be fixable from our end.
I don't know if the tooling lets me distinguish between 1) a NetCore project targeting donet full framework and 2) a dotnet project using PackageReferences

**Comment by kfertitta** [comment]
Yeah, if you just create a .NET Framework console app and use the Package Manager to add a package reference to, say, Newtonsoft.Json, then you'll see that it adds it as a `<PackageReference>`.  Anything requiring `packages.config` is gonna be difficult for most devs to accept, I'm afraid.

**Comment by DamianResler** [comment]
@TimothyMothra It looks like I'm using PackageReference too. I have to agree with @kfertitta, that lack of PackageReference support may be considered problematic.

**Comment by mortenbock** [comment]
I'm having this same issue. I have a .Net Framework webapplication project using PackageReference, and any attempt so far of adding ApplicationInsights via the VS2019 tooling, or the nuget packages has failed.

This is a supported (actually required) setup, in order to reference .Net standard projects from .Net Framework projects. 

This has to be supported in some way by the tooling.

**Comment by EnjoyThisCode** [comment]
I've got the same issue

**Comment by EnjoyThisCode** [comment]
This is the log from the Dependency configuration process:

Configuring Secrets.json (Local) dependency secrets1 in the project...
Installing NuGet packages to project...
Installing package 'Microsoft.Configuration.ConfigurationBuilders.UserSecrets' with version '2.0.0'.
ErrorSystem.InvalidOperationException: Package 'Microsoft.Configuration.ConfigurationBuilders.UserSecrets 2.0.0' is not found in the following primary source(s): 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please verify all your online package sources are available (OR) package id, version are specified correctly.
   at NuGet.PackageManagement.ResolverGather.<GatherAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.ResolverGather.<GatherAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.RunJTFWithCorrectContext(Project project, Func`1 asyncTask)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.WebTools.Shared.VS.NuGet.NuGetPackageManager.<InstallAsync>d__29.MoveNext()
ErrorFailed to configure NuGet packages.
ErrorFailed to configure dependency Secrets.json (Local) secrets1.
