### ISSUE TITLE
Compile Error: InjectXmlLanguage task failed unexpectedly

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1349]
I'm hitting this compile error frequently while building this solution.
I'm recording the details here so I can investigate this when I have the time.

> Error	MSB4018	The "InjectXmlLanguage" task failed unexpectedly.
> 
> Perf	D:\SDK\ApplicationInsights-dotnet-server\AddXmlLanguage.targets	61	
> 
> System.IO.IOException: The process cannot access the file 'D:\SDK\bin\Debug\Src\PerformanceCollector\PerformanceCollector\Microsoft.AI.PerfCounterCollector.XML' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
>    at System.IO.File.ReadAllText(String path)
>    at InlineCode.InjectXmlLanguage.Execute() in c:\Users\tilee\AppData\Local\Temp\vdn2nvfo.0.cs:line 84
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by TimothyMothra** [comment]
I looked at this briefly while working on repo consolidation.
This task in injecting an "english" tag into our xml documentation, I assume that this is for documentation localization support.
I'm surprised that there isn't first-party support for this feature.
Admittedly, this solution was implemented several years ago.
I need a day to investigate if there's been an update to this in the time since, and if not I'd like to implement a more robust feature because i still see this error frequently.
