### ISSUE TITLE
flaky test: Test452OnNet462_XComponentWebAppToWebApi

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1370]
**Error message**
Test method E2ETests.Net462.Test452OnNet462.Test452OnNet462_XComponentWebAppToWebApi threw exception: 
System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.IsTrue failed.

**Stack trace**
   at E2ETests.Test452Base.<ValidateXComponentWebAppToWebApi>d__71.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 1038
--- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at E2ETests.Test452Base.TestXComponentWebAppToWebApi() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 236
   at E2ETests.Net462.Test452OnNet462.Test452OnNet462_XComponentWebAppToWebApi() in E:\A\_work\719\s\Test\E2ETests\E2ETests\net462\Test452OnNet462.cs:line 52

**Comment by TimothyMothra** [comment]
I'm no longer seeing this test fail, so i'm closing this task.
