### ISSUE TITLE
Flaky test QuickPulseServiceClientResubmitsAuthOpaqueHeadersToServiceWithPing

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1386]
```
2018-12-31T20:18:56.9466755Z Failed   QuickPulseServiceClientResubmitsAuthOpaqueHeadersToServiceWithPing
2018-12-31T20:18:56.9483441Z Error Message:
2018-12-31T20:18:56.9484721Z  Assert.IsTrue failed. Not all requests finished processing: expected 2, actual: 1
2018-12-31T20:18:56.9485841Z Stack Trace:
2018-12-31T20:18:56.9487029Z    at Microsoft.ApplicationInsights.Tests.QuickPulseServiceClientTests.WaitForProcessing(Int32 requestCount) in E:\A\_work\428\s\Src\PerformanceCollector\Perf.Shared.Tests\QuickPulse\QuickPulseServiceClientTests.cs:line 2101
2018-12-31T20:18:56.9487466Z    at Microsoft.ApplicationInsights.Tests.QuickPulseServiceClientTests.QuickPulseServiceClientResubmitsAuthOpaqueHeadersToServiceWithPing() in E:\A\_work\428\s\Src\PerformanceCollector\Perf.Shared.Tests\QuickPulse\QuickPulseServiceClientTests.cs:line 1654
2018-12-31T20:18:56.9487668Z 
```

https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8102813

**Comment by TimothyMothra** [comment]
I'm no longer seeing this test fail, so i'm closing this task.
