### ISSUE TITLE
Flaky test QuickPulseServiceClientPingsTheService

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1387]
2018-12-03T23:18:43.8475689Z Failed   QuickPulseServiceClientPingsTheService
2018-12-03T23:18:43.8496425Z Error Message:
2018-12-03T23:18:43.8496855Z  Assert.IsTrue failed. Not all requests finished processing: expected 3, actual: 2
2018-12-03T23:18:43.8498083Z Stack Trace:
2018-12-03T23:18:43.8498808Z    at Microsoft.ApplicationInsights.Tests.QuickPulseServiceClientTests.WaitForProcessing(Int32 requestCount) in D:\a\1\s\Src\PerformanceCollector\Perf.Shared.Tests\QuickPulse\QuickPulseServiceClientTests.cs:line 2104
2018-12-03T23:18:43.8499124Z    at Microsoft.ApplicationInsights.Tests.QuickPulseServiceClientTests.QuickPulseServiceClientPingsTheService() in D:\a\1\s\Src\PerformanceCollector\Perf.Shared.Tests\QuickPulse\QuickPulseServiceClientTests.cs:line 185
2018-12-03T23:18:43.8499266Z 

https://dev.azure.com/mseng/AppInsights/_build/results?buildId=7897752

**Comment by TimothyMothra** [comment]
I'm no longer seeing this test fail, so i'm closing this task.
