### ISSUE TITLE
Flaky test NonExistentCounterWhichUsesPlaceHolder

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1389]
```
**2018-12-03T21:16:19.1618804Z Failed   NonExistentCounterWhichUsesPlaceHolder
2018-12-03T21:16:19.1619498Z Error Message:
2018-12-03T21:16:19.1619703Z  Test method FunctionalTests.Test45.NonExistentCounterWhichUsesPlaceHolder threw exception: 
2018-12-03T21:16:19.1619892Z System.IO.InvalidDataException: Incorrect number of items. Expected: 10 Received: 0
2018-12-03T21:16:19.1620029Z Stack Trace:
2018-12-03T21:16:19.1620193Z     at Functional.Helpers.TelemetryExtensions.ReceiveItemsOfType[T](HttpListenerObservable listener, Int32 count, Int32 timeOut) in D:\a\1\s\Test\PerformanceCollector\FunctionalTests\Serialization\TelemetryExtensions.cs:line 87
2018-12-03T21:16:19.1624137Z    at PerfCounterCollector.FunctionalTests.CommonTests.NonExistentCounterWhichUsesPlaceHolder(HttpListenerObservable listener) in D:\a\1\s\Test\PerformanceCollector\FunctionalTests\CommonTests.cs:line 45
2018-12-03T21:16:19.1624397Z    at FunctionalTests.Test45.NonExistentCounterWhichUsesPlaceHolder() in D:\a\1\s\Test\PerformanceCollector\FunctionalTests\Test45.cs:line 138
2018-12-03T21:16:19.1624528Z 
2018-12-03T21:16:19.1624667Z Standard Output Messages:
2018-12-03T21:16:19.1624793Z  
2018-12-03T21:16:19.1624992Z 
2018-12-03T21:16:19.1625138Z Debug Trace:
2018-12-03T21:16:19.1625283Z Application directory:D:\a\1\a\Release\Test\PerformanceCollector\FunctionalTests\app_NonExistentCounterWhichUsesPlaceHolder
2018-12-03T21:16:19.1625437Z  IIS Port:56769
2018-12-03T21:16:19.1625562Z  Telemetry Port:64610
2018-12-03T21:16:19.1625696Z  Quickpulse Port:58748
2018-12-03T21:16:19.1625844Z  9:15:14 PM:Starting Web host
2018-12-03T21:16:19.1626006Z  vstest.console.exe Information: 0 : Starting IIS Express with configuration file: D:\a\1\a\Release\Test\PerformanceCollector\FunctionalTests\app_NonExistentCounterWhichUsesPlaceHolder\applicationHost.config
2018-12-03T21:16:19.1626186Z  vstest.console.exe Information: 0 : Waiting for iisexpress.exe initialization: pid=1252
2018-12-03T21:16:19.1626332Z  vstest.console.exe Information: 0 : Reading console output of iisexpress.exe: Starting IIS Express ...
2018-12-03T21:16:19.1626513Z  vstest.console.exe Information: 0 : Reading console output of iisexpress.exe: Successfully registered URL "http://localhost:56769/" for site "Development Web Site" application "/"
2018-12-03T21:16:19.1626687Z  vstest.console.exe Information: 0 : Reading console output of iisexpress.exe: Registration completed for site "Development Web Site"
2018-12-03T21:16:19.1626854Z  vstest.console.exe Information: 0 : iisexpress.exe initialization complete: pid=1252
2018-12-03T21:16:19.1626992Z  Etw session started
2018-12-03T21:16:19.1627159Z  9:15:15 PM: FileOverWritten: D:\a\1\a\Release\Test\PerformanceCollector\FunctionalTests\app_NonExistentCounterWhichUsesPlaceHolder\ApplicationInsights.config
2018-12-03T21:16:19.1627326Z  9:15:15 PM: FileOverWritten: D:\a\1\a\Release\Test\PerformanceCollector\FunctionalTests\app_NonExistentCounterWhichUsesPlaceHolder\Web.config
2018-12-03T21:16:19.1637818Z  9:15:15 PM:Starting Web host completed successfully
2018-12-03T21:16:19.1638098Z  9:15:15 PM: Launching application and verifying..
2018-12-03T21:16:19.1638274Z  Application Trace. Level: Always; Id: 65534; Message: ; 
2018-12-03T21:16:19.1638433Z  Application Trace. Level: Verbose; Id: 10; Message: [msg=Log verbose];[msg=No Telemetry Items passed to Enqueue]; 
2018-12-03T21:16:19.1638662Z  ERROR! Every message must have application name as the last parameter to enable StatusMonitor integration: DefaultDomain
2018-12-03T21:16:19.1638897Z  Application Trace. Level: Verbose; Id: 10; Message: [msg=Log verbose];[msg=Storage folder: C:\Users\VssAdministrator\AppData\Local\Microsoft\VSApplicationInsights\vstelAIF-312cbd79-9dbb-4c48-a7da-3cc2a931cb70]; 
2018-12-03T21:16:19.1639105Z  ERROR! Every message must have application name as the last parameter to enable StatusMonitor integration: DefaultDomain
2018-12-03T21:16:19.1639258Z  Application Trace. Level: Verbose; Id: 10; Message: [msg=Log verbose];[msg=No Telemetry Items passed to Enqueue]; 
2018-12-03T21:16:19.1639428Z  ERROR! Every message must have application name as the last parameter to enable StatusMonitor integration: DefaultDomain
2018-12-03T21:16:19.1639610Z  Application Trace. Level: Verbose; Id: 10; Message: [msg=Log verbose];[msg=Storage folder: C:\Users\VssAdministrator\AppData\Local\Microsoft\VSApplicationInsights\vstelAIF-312cbd79-9dbb-4c48-a7da-3cc2a931cb70]; 
2018-12-03T21:16:19.1639794Z  ERROR! Every message must have application name as the last parameter to enable StatusMonitor integration: DefaultDomain
2018-12-03T21:16:19.1640457Z  Application Trace. Level: Verbose; Id: 10; Message: [msg=Log verbose];[msg=No Telemetry Items passed to Enqueue]; 
2018-12-03T21:16:19.1640617Z  ERROR! Every message must have application name as the last parameter to enable StatusMonitor integration: DefaultDomain
2018-12-03T21:16:19.1640807Z  Application Trace. Level: Verbose; Id: 10; Message: [msg=Log verbose];[msg=Storage folder: C:\Users\VssAdministrator\AppData\Local\Microsoft\VSApplicationInsights\vstelf144292e-e3b2-4011-ac90-20e5c03fbce5]; 
2018-12-03T21:16:19.1645492Z  ERROR! Every message must have application name as the last parameter to enable StatusMonitor integration: DefaultDomain
2018-12-03T21:16:19.1645970Z  9:15:17 PM: Launching application and verifying success.
2018-12-03T21:16:19.1647034Z  =>
2018-12-03T21:16:19.1647556Z  Item received: {"name":"Microsoft.ApplicationInsights.Dev.fafa4b1003d34bb098f4364f0bdf5df8.Message","time":"2018-12-03T21:15:17.5912987Z","iKey":"fafa4b10-03d3-4bb0-98f4-364f0bdf5df8","tags":{"ai.cloud.roleInstance":"factoryvm-az20","ai.operation.syntheticSource":"SDKTelemetry","ai.internal.sdkVersion":"dotnet:2.9.0-3628"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"AI (Internal): [Microsoft-ApplicationInsights-Extensibility-Web] Failed to add target instrumentation key hash as a response header. Exception System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule.AddTargetHashForResponseHeader(HttpContext context) in D:\\a\\1\\s\\Src\\Web\\Web.Shared.Net\\RequestTrackingTelemetryModule.cs:line 239\r\n   at Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule.<.ctor>b__8_0(HttpContext httpContext) in D:\\a\\1\\s\\Src\\Web\\Web.Shared.Net\\ApplicationInsightsHttpModule.cs:line 71","properties":{"DeveloperMode":"true"}}}}
2018-12-03T21:16:19.1648382Z  <=
2018-12-03T21:16:19.1648540Z  Application Trace. Level: Always; Id: 65534; Message: ; 
2018-12-03T21:16:19.1654571Z  Application Trace. Level: Always; Id: 65534; Message: ; 
2018-12-03T21:16:19.1654801Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=Log verbose];[msg=No Telemetry Items passed to Enqueue]; 
2018-12-03T21:16:19.1655009Z  Application Trace. Level: Verbose; Id: 7; Message: A scheduler timer was created for the interval: 300000; 
2018-12-03T21:16:19.1655187Z  Application Trace. Level: Always; Id: 65534; Message: ; 
2018-12-03T21:16:19.1655326Z  Application Trace. Level: Verbose; Id: 42; Message: Injection started.; 
2018-12-03T21:16:19.1655513Z  Application Trace. Level: Informational; Id: 43; Message: MVC Injection failed. Error message: Microsoft.ApplicationInsights.Web.Implementation.ExceptionHandlersInjector+ResolutionException: Failed to get System.Web.Mvc.HandleErrorAttribute, System.Web.Mvc type
2018-12-03T21:16:19.1655718Z     at Microsoft.ApplicationInsights.Web.Implementation.ExceptionHandlersInjector.GetTypeOrFail(String typeName) in D:\a\1\s\Src\Web\Web.Shared.Net\Implementation\ExceptionHandlersInjector.cs:line 630
2018-12-03T21:16:19.1655959Z     at Microsoft.ApplicationInsights.Web.Implementation.ExceptionHandlersInjector.AddMvcFilter(TelemetryClient telemetryClient, ModuleBuilder moduleBuilder, ConstructorInfo exceptionTelemetryCtor, MethodInfo trackExceptionMethod) in D:\a\1\s\Src\Web\Web.Shared.Net\Implementation\ExceptionHandlersInjector.cs:line 108; 
2018-12-03T21:16:19.1656160Z  Application Trace. Level: Verbose; Id: 47; Message: Injection completed.; 
2018-12-03T21:16:19.1656321Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=WebModuleCallback];[callback=OnBegin];[uri=http://localhost:56769/aspx/TestWebForm.aspx];; 
2018-12-03T21:16:19.1656523Z  Application Trace. Level: Warning; Id: 36; Message: Failed to add target instrumentation key hash as a response header. Exception System.NullReferenceException: Object reference not set to an instance of an object.
2018-12-03T21:16:19.1656804Z     at Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule.AddTargetHashForResponseHeader(HttpContext context) in D:\a\1\s\Src\Web\Web.Shared.Net\RequestTrackingTelemetryModule.cs:line 239
2018-12-03T21:16:19.1656989Z     at Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule.<.ctor>b__8_0(HttpContext httpContext) in D:\a\1\s\Src\Web\Web.Shared.Net\ApplicationInsightsHttpModule.cs:line 71; 
2018-12-03T21:16:19.1657171Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=Log verbose];[msg=StartRunnerEvent set as Buffer is full.]; 
2018-12-03T21:16:19.1657887Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=Log verbose];[msg=StartRunnerEvent set as Buffer is full.]; 
2018-12-03T21:16:19.1658200Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=Log verbose];[msg=StartRunnerEvent set as Buffer is full.]; 
2018-12-03T21:16:19.1658353Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=Log verbose];[msg=StartRunnerEvent set as Buffer is full.]; 
2018-12-03T21:16:19.1658529Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=Log verbose];[msg=StartRunnerEvent set as Buffer is full.]; 
2018-12-03T21:16:19.1658677Z  Application Trace. Level: Verbose; Id: 3; Message: [msg=Log verbose];[msg=StartRunnerEvent set as Buffer is full.]; 
2018-12-03T21:16:19.1658856Z  Application Trace. Level: Always; Id: 65534; Message: ; 
2018-12-03T21:16:19.1659030Z  Application Trace. Level: Always; Id: 65534; Message: ; 
2018-12-03T21:16:19.1659196Z  vstest.console.exe Information: 0 : Stopping iisexpress.exe: pid=1252
2018-12-03T21:16:19.1659337Z  vstest.console.exe Information: 0 : Waiting for exit of iisexpress.exe: pid=1252
2018-12-03T21:16:19.1856610Z  vstest.console.exe Information: 0 : iisexpress.exe successfully exited: pid=1252
2018-12-03T21:16:19.1857468Z  Etw session stopped
2018-12-03T21:16:19.2211348Z 
```

https://dev.azure.com/mseng/AppInsights/_build/results?buildId=7896651

**Comment by TimothyMothra** [comment]
I'm no longer seeing this test fail, so i'm closing this task.
