### ISSUE TITLE
AccountIdTelemetryInitializer fails with IndexOutOfRangeException

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet#141]
AI (Internal): TelemetryInitializer Microsoft.ApplicationInsights.Web.AccountIdTelemetryInitializer filed to initialize telemetry item System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.ApplicationInsights.Web.AccountIdTelemetryInitializer.GetAuthUserContextFromUserCookie(HttpCookie authUserCookie, RequestTelemetry requestTelemetry)
   at Microsoft.ApplicationInsights.Web.AccountIdTelemetryInitializer.OnInitializeTelemetry(HttpContext platformContext, RequestTelemetry requestTelemetry, ITelemetry telemetry)
   at Microsoft.ApplicationInsights.Web.Implementation.WebTelemetryInitializerBase.Initialize(ITelemetry telemetry)

**Comment by abaranch** [comment]
Not Core, but Web SDK issue. Will be fixed in 2.0.0-beta4.
