### ISSUE TITLE
`Microsoft.ServiceProfiler.EventPipe.Orchestration.OnDemandSchedulingPolicy` exceptions

### ISSUE THREAD

**Issue by SidShetye** [microsoft/ApplicationInsights-dotnet#1534]
## Repro Steps
This error is thrown by our ASP.NET Core apps during runtime if we use AppInsights. We're not able to find any pattern in their occurrence. However, when it does happen, we notice it happens across multiple instances and apps in the same time frame.

##  Actual Behavior
Application logs show the following errors

### Windows OS

```
2020-01-08 00:09:29.740 +00:00 [Error] Microsoft.ServiceProfiler.EventPipe.Orchestration.OnDemandSchedulingPolicy:
Failed fetching the next scheduling for policy OnDemandSchedulingPolicy
Microsoft.ServiceProfiler.Agent.FrontendClient.RequestTimeOutException: api/profileragent/v4/settings?iKey=<removedFromLog>&featureVersion=1.0.0&oldTimestamp=2019-06-11T20:32:12.0000000Z
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.<>c__DisplayClass11_0`1.<b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.<>c__DisplayClass11_0`1.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.HttpRequestAsync[T](Func`1 lazyRequestPath, CancellationToken cancellationToken, String callingFunctionName, Func`2 onSuccess, Func`1 requestFunction, Func`1 onNotModified, Func`1 onBadRequest, Func`1 onUnauthorized)
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.HttpGetAsync[T](Func`1 lazyRequestPath, CancellationToken cancellationToken, Func`2 onSuccess, Func`1 onNotModified, Func`1 onUnauthorized, String callingFunctionName)
   at Microsoft.ServiceProfiler.Agent.FrontendClient.ProfilerFrontendClient.GetProfilerSettingsAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceProfiler.EventPipe.Orchestration.OnDemandSchedulingPolicy.GetScheduleAsync()
   at Microsoft.ServiceProfiler.Orchestration.SchedulingPolicy.StartPolicyAsync(CancellationToken token)
```

### Linux 

```
2020-01-08 00:07:42.140 +00:00 [Error] Microsoft.ServiceProfiler.EventPipe.Orchestration.OnDemandSchedulingPolicy:
Failed fetching the next scheduling for policy OnDemandSchedulingPolicy
Microsoft.ServiceProfiler.Agent.FrontendClient.RequestTimeOutException: api/profileragent/v4/settings?iKey=<removedFromLog>&featureVersion=1.0.0&oldTimestamp=2019-06-11T20:32:12.0000000Z
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.<>c__DisplayClass11_0`1.<b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.<>c__DisplayClass11_0`1.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.HttpRequestAsync[T](Func`1 lazyRequestPath, CancellationToken cancellationToken, String callingFunctionName, Func`2 onSuccess, Func`1 requestFunction, Func`1 onNotModified, Func`1 onBadRequest, Func`1 onUnauthorized)
   at Microsoft.ServiceProfiler.Agent.FrontendClient.StampFrontendClient.HttpGetAsync[T](Func`1 lazyRequestPath, CancellationToken cancellationToken, Func`2 onSuccess, Func`1 onNotModified, Func`1 onUnauthorized, String callingFunctionName)
   at Microsoft.ServiceProfiler.Agent.FrontendClient.ProfilerFrontendClient.GetProfilerSettingsAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceProfiler.EventPipe.Orchestration.OnDemandSchedulingPolicy.GetScheduleAsync()
   at Microsoft.ServiceProfiler.Orchestration.SchedulingPolicy.StartPolicyAsync(CancellationToken token)
-
```

## Expected Behavior
Application Insights works properly and doesn't have errors

## Version Info 
- SDK Version : 
```
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.12.0" />
<PackageReference Include="Microsoft.ApplicationInsights.Profiler.AspNetCore" Version="2.0.0-beta5" />
<PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.12.0" />
```
- .NET Version : .NET Core 3.1
- How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS with .csproj
- OS : Both Windows (Microsoft Windows NT 10.0.14393.0) as well as Linux (Unix 4.4.0.128)
- Hosting Info (IIS/Azure WebApps/ etc) : Azure App Service (multiple instances and apps, both Windows and Linux)

**Comment by Dmitry-Matveev** [comment]
@pharring , can you please take a look at new exception reported for Snapshot Collector: "Failed fetching the next scheduling for policy OnDemandSchedulingPolicy"?
