### ISSUE TITLE
Can't get profiler-based dependency tracking to work anymore

### ISSUE THREAD

**Issue by tomasr** [microsoft/ApplicationInsights-dotnet#1593]
I've been struggling for the past few weeks trying to get profiler-based dependency tracking working again on my local dev box, and can't seem to figure out what is going on. This broke at some point after updating to 2.4.x, as it was definitely working before!

OS: Windows 10 - (10.0.15063.0)
Most recent release of Status Monitor installed (have also tried uninstalling and reinstalling).

From what I can see in the event logs, the profiler attached correctly to the IIS worker processes:
```
.NET Runtime version 4.0.30319.1 - The profiler was loaded successfully.  Profiler CLSID: '{324F817A-7420-4E6D-B3C1-143FBED6D855}'.  Process ID (decimal): 8420.  Message ID: [0x2507].
```
Profiler key in the registry clearly points to the right location:

![image](https://user-images.githubusercontent.com/16179/28676109-656cd430-72af-11e7-9b76-3e530efb5801.png)

In code, I can see that `Decorator.IsHostEnabled()` returns `true` (but then again, it seems that's the default value, so it's probably not very useful), however, any call to attempt to decorate a method fails saying the profiler is not active.

Here's output from an ETW trace showing the issue:

![image](https://user-images.githubusercontent.com/16179/28676026-2470c626-72af-11e7-98f3-85594f2c93f5.png)

```
System.InvalidOperationException: Instrumentation Agent is not active
         at Microsoft.Diagnostics.Instrumentation.Extensions.Base.Callbacks.Add(Int32 methodId, Func`3 onBegin, Func`5 onEnd, Action`4 onException)
         at Microsoft.Diagnostics.Instrumentation.Extensions.Intercept.Decorator.Decorate(String assemblyName, String moduleName, String methodName, UInt32 argsCount, Func`3 beginCallback, Func`5 endCallback, Action`4 exceptionCallback)
         at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ProfilerRuntimeInstrumentation.DecorateProfilerForHttp(ProfilerHttpProcessing& httpCallbacks)
         at Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule.InitializeForRuntimeProfiler()
         at Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule.InitializeForRuntimeInstrumentationOrFramework()
```

I suspect there must be some issue when the profiler is attaching to the process and it's not correctly binding the agent assembly methods, but I do not know if there is some other ETW provider or something similar I can enable to get data out of it. Is there any way to log what the native profiler is doing?

**Comment by cijothomas** [comment]
Closing old issue without repros.
