### ISSUE TITLE
Unhandled exception. System.Diagnostics.Tracing.EventSourceException

### ISSUE THREAD

**Issue by wortho** [microsoft/ApplicationInsights-dotnet#1639]
My aspnetcore application crashes frequently with 

> Unhandled exception. System.Diagnostics.Tracing.EventSourceException

It usually crashes after running for about a minute.

Workaround: I disabled ApplicationInsightsServiceOptions.EnableEventCounterCollectionModule
After disabling this module in ConfigureServices the application no longer crashes.
```
services.AddApplicationInsightsTelemetry(options => {
                options.EnableEventCounterCollectionModule = false;
            });
```

##  Actual Behavior
Application crashes after about a minute with exception:
```
Unhandled exception. System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener.
 ---> System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'level')
Actual value was LogAlways.

```
## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore" Version="2.12.0
.NET Version :dotnet --version 3.1.101	 		

Complete stack trace.
```
Unhandled exception. System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener.
 ---> System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'level')
Actual value was LogAlways.
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.MapLevel(EventLevel level)
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.LogEvent(EventWrittenEventArgs eventData)
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.<.ctor>b__4_0(EventWrittenEventArgs e, String s)
   at Azure.Core.Diagnostics.AzureEventSourceListener.OnEventWritten(EventWrittenEventArgs eventData)
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   --- End of inner exception stack trace ---
```

**Comment by Dmitry-Matveev** [comment]
@cijothomas , can you please take a look, as per description it might be related to Event Counters collection module?

**Comment by wortho** [comment]
@cijothomas Did you get to look into this?
