### ISSUE TITLE
Flaky Test: WebApi.FunctionalTests.FunctionalTest.ExceptionTelemetryWebApiTests.TestBasicRequestPropertiesAfterRequestingControllerThatThrows

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1671]
I'm seeing this test fail frequently:

```
[xUnit.net 00:00:05.4325976]       actual.Duration '00:00:00.0387438' is not less than timer.Elpased '00:00:00.0154093'
[xUnit.net 00:00:05.4326745]       Expected: True
[xUnit.net 00:00:05.4327267]       Actual:   False
##[error][xUnit.net 00:00:05.4309248]     WebApi.FunctionalTests.FunctionalTest.ExceptionTelemetryWebApiTests.TestBasicRequestPropertiesAfterRequestingControllerThatThrows [FAIL]
[xUnit.net 00:00:05.4337861]       Stack Trace:
[xUnit.net 00:00:05.4351258]         E:\A\_work\20\s\NETCORE\test\FunctionalTestUtils\TelemetryTestsBase.cs(64,0): at FunctionalTestUtils.TelemetryTestsBase.ValidateBasicRequest(InProcessServer server, String requestPath, RequestTelemetry expected)
[xUnit.net 00:00:05.4354944]         E:\A\_work\20\s\NETCORE\test\WebApi.FunctionalTests\FunctionalTest\ExceptionTelemetryWebApiTests.cs(33,0): at WebApi.FunctionalTests.FunctionalTest.ExceptionTelemetryWebApiTests.TestBasicRequestPropertiesAfterRequestingControllerThatThrows()
[xUnit.net 00:00:05.7104819]   Finished:    WebApi.FunctionalTests.Tests
```

**Comment by TimothyMothra** [comment]
TODO: move this to my other flaky test tracking issue and close
