### ISSUE TITLE
Dependency issue to System.Memory with Microsoft.ApplicationInsights.Web

### ISSUE THREAD

**Issue by itcotta** [microsoft/ApplicationInsights-dotnet#1899]
I've added Microsoft.ApplicationInsights.Web, Microsoft.ApplicationInsights.TraceListener and Microsoft.ApplicationInsights.Log4NetAppender to a .NET Framework 4.7.1 web project which is being hosted on Azure.

The issue I'm experincing is that this exception is being logged into the application insights log:

```
AI (Internal): [Microsoft-ApplicationInsights-Extensibility-DependencyCollector] Callback 'OnBeginSql' failed for id = '_'. Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Diagnostics.Activity.TrySetTraceIdFromParent()
   at System.Diagnostics.Activity.GenerateW3CId()
   at System.Diagnostics.Activity.Start()
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ClientServerDependencyTracker.BeginTracking(TelemetryClient telemetryClient) in E:\A\_work\21\s\WEB\Src\DependencyCollector\Shared\Implementation\ClientServerDependencyTracker.cs:line 44
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.FrameworkSqlProcessing.OnBeginExecuteCallback(Int64 id, String dataSource, String database, String commandText) in E:\A\_work\21\s\WEB\Src\DependencyCollector\Shared\Implementation\FrameworkSqlProcessing.cs:line 64

```
From what I can see Microsoft.ApplicationInsights.Web is dependant on package version 4.5.4 of System.Memory. This version makes use version 4.0.1.1 of the System.Memory dll.
However the exception is claiming that something internally is using System.Memory version 4.0.1.0. 

I tried adding

```
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
```

into the web.config but this didn't solve the issue where the exception is being logged.

**Comment by rajkumar-rangaraj** [comment]
Please refer #1707

**Comment by cijothomas** [comment]
Closing as duplicate with same underlying issue.
