### ISSUE TITLE
TypeInitializationException thrown for trimmed applications (worked in beta2 and prior)

### ISSUE THREAD

**Issue by pinkfloydx33** [microsoft/ApplicationInsights-dotnet#2058]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
  - Primary:
    - Microsoft.ApplicationInsights 2.15.0-beta3 **or** 2.15.0
  - Secondary:
    - Microsoft.ApplicationInsights.WorkerService 2.15.0-beta3 **or** 2.15.0
    - (or)  Microsoft.ApplicationInsights.AspNetCore 2.15.0-beta3 **or** 2.15.0

* Runtime version: netcoreapp3.1
* Hosting environment: Windows (local), Linux (Kubernetes)

### Describe the bug

After upgrading from 2.15.0-beta2 to 2.15.0-beta3 (and again verified in 2.15.0), a dotnet application published with `PublishTrimmed=true` throws a `TypeInitializationException`. In my case it occurs when something within the `Options` infrastructure modifies `TelemetryConfiguration.DisableTelemetry`. In the attached repro, simply calling `TelemetryClient.Flush` will raise the exception. 

The source of the exception itself comes from `System.Diagnostics.Tracing.CounterGroup` (through a chain of `ctor`/`cctor` invocations). I've tried adding the Application Insights assemblies as well as all of the System.Diagnostics assemblies as Trimming Roots and/or marking them as non-trimmable. 

This issue did not exist in version 2.15.0-beta2. However, I am unsure if this is due to AI or because of something in one of its dependencies.

### To Reproduce

I've attached two files: 
- Program.cs
- AppInsightsTrimmed.csproj

Run the following commands:
```bash
dotnet publish -o .\working --self-contained=true -r win-x64 -c Release /p:PublishTrimmed=false
.\working\AppInsightsTrimmed.exe
```
Output:
> Complete

Run the following commands:
```bash
dotnet publish -o .\broke --self-contained=true -r win-x64 -c Release /p:PublishTrimmed=true
.\broke\AppInsightsTrimmed.exe
```
Output:
> Failed
> System.TypeInitializationException: The type initializer for
>'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' threw an exception.

Different from my personal scenario, the TIE is thrown in the repro when calling Flush. The stack traces otherwise are identical (beginning with `CoreEventSource` and on). I've attached the stack trace from the repro as well.

[TrimmingRepo.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/5233240/TrimmingRepo.zip)
[StackTrace-MyProject.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/5233242/StackTrace-MyProject.txt)
[StackTrace-Repo.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/5233243/StackTrace-Repo.txt)

**Comment by cijothomas** [comment]
@rajkumar-rangaraj Can you take a look?
(Anything about the ingestionstat eventcounter?)

**Comment by rajkumar-rangaraj** [comment]
EventCounter to track `Ingestion endpoint response time` is a part of `2.15.0-beta1`. `Ingestion service data delivery status` is a part of `2.15.0-beta3`, but it does not touch the `CoreEventSource` ctor. I will investigate an issue with attached repro.

**Comment by rajkumar-rangaraj** [comment]
@pinkfloydx33 
I could not recreate an issue, for both the scenario I got the same output.

```
D:\TrimmingRepo>dotnet publish -o .\working --self-contained=true -r win-x64 -c Release /p:PublishTrimmed=false
Microsoft (R) Build Engine version 16.7.0-preview-20220-01+80e487bff for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\TrimmingRepo\AppInsightsTrimmed.csproj (in 839 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  AppInsightsTrimmed -> D:\TrimmingRepo\bin\Release\netcoreapp3.1\win-x64\AppInsightsTrimmed.dll
  AppInsightsTrimmed -> D:\TrimmingRepo\working\

D:\TrimmingRepo>.\working\AppInsightsTrimmed.exe
Complete

D:\TrimmingRepo>dotnet publish -o .\broke --self-contained=true -r win-x64 -c Release /p:PublishTrimmed=true
Microsoft (R) Build Engine version 16.7.0-preview-20220-01+80e487bff for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  AppInsightsTrimmed -> D:\TrimmingRepo\bin\Release\netcoreapp3.1\win-x64\AppInsightsTrimmed.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  AppInsightsTrimmed -> D:\TrimmingRepo\broke\

D:\TrimmingRepo>.\broke\AppInsightsTrimmed.exe
Complete
```

**Comment by pinkfloydx33** [comment]
I wonder if maybe it could be related to the SDK in use then? I recieve the error both in my (very minimal) repro and in my actual project both locally and when built/deployed in docker. My coworker was able to verify the issue locally with the attached repro as well. 

I'm not at my desk, so I can't print out `dotnet --info` at the moment, but in both instances I am using the latest SDK (from a few days ago) v3.1.402 and runtime 3.1.8

**Comment by pinkfloydx33** [comment]
I've run the reproduction on two other computers and had another co-worker try it. In all instances the second command fails.

In case it might matter, `dotnet --info` for my machine looks like the following:

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.402
>  Commit:    9b5de826fd
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19041
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.402\
> 
> Host (useful for support):
>   Version: 3.1.8
>   Commit:  9c1330dedd
> 
> .NET Core SDKs installed:
>   3.1.301 [C:\Program Files\dotnet\sdk]
>   3.1.302 [C:\Program Files\dotnet\sdk]
>   3.1.402 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Note that I've tried adding a global.json to the repro using `3.1.302` with `rollForward` disabled and the execution still fails.

**Comment by collinbarrett** [comment]
ah, yep, this issue was biting me too, I think. just rolled back in ^that commit and I'm seeing metrics reported again.

**Comment by joergjo** [comment]
I've just run into the same issue with ASP.NET Core 3.1.9 and App Insights 2.15. A trimmed Alpine container image build deployed to Kubernetes fails on startup with
```
ERROR: System.TypeInitializationException: The type initializer for 'Microsoft.ApplicationInsights.Extensibility.Impleme
ntation.Tracing.CoreEventSource' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an
 instance of an object.
   at System.Diagnostics.Tracing.CounterGroup.OnEventSourceCommand(Object sender, EventCommandEv
entArgs e)
   at System.Diagnostics.Tracing.EventSource.add_EventCommandExecuted(EventHandler`1 value)
   at System.Diag
nostics.Tracing.CounterGroup.RegisterCommandCallback()
   at System.Diagnostics.Tracing.CounterGroup..ctor(EventSource e
ventSource)
   at System.Diagnostics.Tracing.CounterGroup.GetCounterGroup(EventSource eventSource)
   at System.Diagnost
ics.Tracing.DiagnosticCounter..ctor(String name, EventSource eventSource)
   at System.Diagnostics.Tracing.EventCounter.
.ctor(String name, EventSource eventSource)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Cor
eEventSource..ctor()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource..cctor()

  --- End of inner exception stack trace ---
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryC
onfigurationFactory.SelectInstrumentationKey(TelemetryConfiguration configuration)
   at Microsoft.ApplicationInsights.E
xtensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModu
les modules, String serializedConfiguration)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryC
onfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules)
   at Microsoft.Applicati
onInsights.Extensibility.TelemetryConfiguration.CreateDefault()
   at Microsoft.Extensions.DependencyInjection.Telemetry
ConfigurationOptions..ctor(IEnumerable`1 configureOptions, IOptions`1 applicationInsightsServiceOptions)
   at System.Ru
ntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExcept
ions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters,
 CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(S
erviceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntim
eResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProvide
rEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResol
ver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.Depende
ncyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft
.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCa
llSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.V
isitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLoo
kup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineSc
ope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Ca
llSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.
Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argumen
t)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCall
Site enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Ca
llSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInj
ection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, Servic
eProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection
.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite,
TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructo
r(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjectio
n.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extens
ions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverConte
xt context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.D
ependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolv
erContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceC
allSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolv
er.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.
DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   a
t Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, Ru
ntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Micr
osoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallS
ite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.Visi
tCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Cal
lSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Mic
rosoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgum
ent argument)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCal
lSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lo
ckType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallS
ite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Call
SiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection
.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext
context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSit
e callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Vis
itCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, Runt
imeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRoot
Cache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.
ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.D
ependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope sc
ope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<Rea
lizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceP
roviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extens
ions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.Dep
endencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProv
iderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.Depende
ncyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extension
s.Hosting.HostBuilder.Build()
   at Oakton.AspNetCore.NetCoreInput.BuildHost()
   at Oakton.AspNetCore.RunCommand.Execut
e(RunInput input)
   at Oakton.OaktonCommand`1.Oakton.IOaktonCommand.Execute(Object input)
   at Oakton.CommandRun.Execu
te()
   at Oakton.CommandExecutor.execute(CommandRun run)
```
 
Switching back to an untrimmed build solves the issue.

**Comment by aelij** [comment]
I can confirm this repros on Linux with a trimmed image. Package v2.15.0 (final).

**Comment by ohadschn** [comment]
Does this repro on [2.16.0-beta1](https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.16.0-beta1)?

**Comment by pinkfloydx33** [comment]
> Does this repro on [2.16.0-beta1](https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.16.0-beta1)?

Yes

**Comment by pinkfloydx33** [comment]
After installing net5.0 and updating the TargetFramework to `net5.0`, the problem no longer exists. 
Keeping the target framework at `netcoreapp3.1` but using the 5.0 tooling works as well

**Comment by dhaval24** [comment]
@cijothomas @rajkumar-rangaraj I faced this issue recently as well. I face the same issue when running on Ubuntu 18.04 docker container. Additionally, I also saw a behavior when I used trimmed binary my custom `TelemetryInitializer`'s initialize method never gets called.

When running the same exe on the windows where all the dependencies are there I get it to work.

**Comment by azchohfi** [comment]
Can we reopen this issue? I'm having multiple IL2104 a .NET6 app. This means that Microsoft.AppInsights doesn't support trimming, which is a big issue, especially with .NET7 around the corner and its stable release of Native AOT, which requires trimming.
