### ISSUE TITLE
NullReferenceException in Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.OnBufferFull() due to data race on this.startRunnerEvent

### ISSUE THREAD

**Issue by elmerjfudd** [microsoft/ApplicationInsights-dotnet#2261]
### Bug Description

We downloaded and built dc4d434141693a6ccb6af2e3d2f297231270eab5 from source (runtime ```net46```) on a Windows 10 Home Edition machine. While running the test suite, we observed the following NullReferenceException bug:

```
Failed SendingLogicMarkedAsInternalSdkOperation [254 ms]
Error Message:
Test method Microsoft.ApplicationInsights.Channel.InMemoryTransmitterTests+SendingInterval.SendingLogicMarkedAsInternalSdkOperation threw exception:
System.NullReferenceException: Object reference not set to an instance of an object.
  Stack Trace:
      at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.OnBufferFull() in D:\GitBench\BugRepos\ApplicationInsights-dotnet\Source\BASE\src\Microsoft.ApplicationInsights\Channel\InMemoryTransmitter.cs:line 123
   at Microsoft.ApplicationInsights.Channel.InMemoryTransmitterTests.SendingInterval.SendingLogicMarkedAsInternalSdkOperation() in D:\GitBench\BugRepos\ApplicationInsights-dotnet\Source\BASE\Test\Microsoft.ApplicationInsights.Test\Microsoft.ApplicationInsights.Tests\Channel\InMemoryTransmitterTests.cs:line 57
```

After further investigation, it looks like a data race between the object allocation ```this.startRunnerEvent = new AutoResetEvent(false)``` in ```InMemoryTrransmitter::Runner()``` (here: https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Channel/InMemoryTransmitter.cs#L100) and the object use ```this.startRunnerEvent.Set()``` in ```InMemoryTransmitter::OnBufferFull()``` (here: https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Channel/InMemoryTransmitter.cs#L123). 

As an aside, we observe ```SendingLogicMarkedAsInternalSdkOperation``` failing with the ```net461``` runtime and it looks like the issue goes back to mid-2018.

### How To Reproduce

The data race happens sporadically. However, we can enhance it by adding a ```Thread.Sleep(100)``` before the allocation in ```InMemoryTrransmitter::Runner()``` (note: even a ```10ms``` delay triggers the bug consistently on our machines; you may have to try with other values):

```
try
{
  Thread.Sleep(100); // <--- added thread sleep operation here
  using (this.startRunnerEvent = new AutoResetEvent(false))
  ...
```

To confirm that ```this.startRunnerEvent``` is the culprit, we further added an assert in ```InMemoryTrransmitter::Runner()``` that gets triggered when running ```SendingLogicMarkedAsInternalSdkOperation``` 

```
private void OnBufferFull()
{
  System.Diagnostics.Debug.Assert(this.startRunnerEvent != null, "this.startRunnerEvent is null"); // <--- added assert here
  this.startRunnerEvent.Set();
  CoreEventSource.Log.LogVerbose("StartRunnerEvent set as Buffer is full.");
}
```

**Comment by elmerjfudd** [comment]
Any updates on this issue? :-)

**Comment by elmerjfudd** [comment]
Circled around and this data race is still happening with the latest commit.

**Comment by elmerjfudd** [comment]
Circled around to check on this issue and the bug still occurs with the latest commit.

**Comment by elmerjfudd** [comment]
This issue still occurs with the most recent commit, i.e., ed0015a
I was wondering if there is any fix currently in the works.

**Comment by elmerjfudd** [comment]
Re-opening because the bug still gets triggered with the most recent major release.
