### ISSUE TITLE
Crash on restart/upgrade of Azure App Service possibly due to old SnapshotCollector reference

### ISSUE THREAD

**Issue by garywebb** [microsoft/ApplicationInsights-dotnet#2266]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights.Web Version=2.17.0, Microsoft.ApplicationInsights.AspNetCore Version=2.17.0
* Runtime version : netcoreapp3.1
* Hosting environment : Azure Web App on Azure App Service

### Describe the bug

We see an exception in the event logs (below) when shutting down our application. The exception is identical to the one found in [Snapshot Collector Uploader crashes on IIS shutdown](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2097)

In the above issue the user also reported that the exception was thrown when their application was shutting down due to an issue within the SnapshotCollector when running on IIS. The issue was fixed by upgrading SnapshotCollector to v1.3.7.5. 

We do not reference SnapshotCollector directly and are running on Azure App Service instead of IIS directly.  so aren't able to upgrade to fix the issue.

However, as part of our investigation we found that one of the App Insights packages references a version of the SnapshotCollector which does not have the fix described in the Issue above in it, which may explain our crashes: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ - this package uses v1.3.7.3, whereas the fix is in v1.3.7.5.

Exception:
```
Application: w3wp.exe
CoreCLR Version: 4.700.21.11102
.NET Core Version: 3.1.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (The semaphore has been disposed.)
 ---&gt; System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at Microsoft.ApplicationInsights.SnapshotCollector.Pipeline.ProducerConsumerQueue`1.Produce(T workItem)
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.EnqueueRequest(Request request)
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Shutdown()
   at System.Threading.CancellationToken.&lt;&gt;c.&lt;.cctor&gt;b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.&lt;&gt;c.&lt;ExecuteCallback&gt;b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.ApplicationInsights.SnapshotCollector.ApplicationLifetimeManager.Stop()
   at Microsoft.ApplicationInsights.SnapshotCollector.AssemblyLoadContextLifetimeManager.OnUnloading(Object sender)
   at System.Runtime.Loader.AssemblyLoadContext.RaiseUnloadEvent()
   at System.Runtime.Loader.AssemblyLoadContext.OnProcessExit()
   at System.AppContext.OnProcessExit()
```

### To Reproduce

We are unsure of the exact steps required to reproduce this issue. We see the issue on one of our environments, but not others, with the error only reported in the short lived eventlog.xml file and only visible (without looking at the eventlog) on restart, so we're uncertain when exactly it started and the change that might have caused it.

@pharring was aware of the issue (in the above ticket) and seemed to understand the cause, so may be able to help in reproducing this error.

**Comment by pharring** [comment]
It sounds like we should update the reference in WebJobs.Logging. I see you already opened an [issue](https://github.com/Azure/azure-webjobs-sdk/issues/2714) there. Thank you!
In the meantime, you can workaround it by manually adding a PackageReference to SnapshotCollector 1.3.7.5 in your application.

**Comment by pharring** [comment]
Closing this issue in favor of the WebJobs.Logging issue.
