### ISSUE TITLE
DequeueAndSend throws WebException

### ISSUE THREAD

**Issue by didddy** [Microsoft/ApplicationInsights-dotnet#230]
...happens in our Release but not in Debug build. Someone has an idea why?

EventId : 3, Level : Verbose, Message : [msg=Log verbose];[msg=DequeueAndSend: Failed Sending: Exception: System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.DequeueAndSend()], Payload : [msg : DequeueAndSend: Failed Sending: Exception: System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.DequeueAndSend()] [appDomainName : Application.exe] , EventName : LogVerboseInfo, Timestamp : 2016-05-10T17:41:08.5150330Z, ProcessId : 27292, ThreadId : 12692

**Comment by abaranch** [comment]
Please check what settings you have for request length and timeout. For web that would be in web.config.

**Comment by didddy** [comment]
Thx for your advice but checking timeouts and sizes didn't solve my issue. As I can not reproduce this with a test application I have to dig deeper in my application. I'll let you know if I find something...

**Comment by dnduffy** [comment]
My suspicion is that you have an asynchronous threading issue and the process is getting interrupted and torn down before it finishes.

**Comment by didddy** [comment]
Finally I was able to find the issue: System.Runtime.dll (we still use 4.0) was missing in my setup file and therefore not installed... that explains why it worked while Debug but not on the target system.
It was so hard to find because there is no handling of exceptions at SendRequestAsync failing with just "'System.IO.FileNotFoundException' in Microsoft.ApplicationInsights.dll"

**Comment by abaranch** [comment]
Thank you for the update. Great that you finally figured that out.
