### ISSUE TITLE
TelemetryConfiguration.CreateDefault () crashes on MacOS

### ISSUE THREAD

**Issue by sergeysolod17** [microsoft/ApplicationInsights-dotnet#2436]
Hello!

I have a problem sending telemetry from Azur Functions. When I run the code on Windows(locally and in cloud) with .NET 6.0.100-rc1 installed - everything is OK, but when I run it on MacOS - it crashes when TelemetryConfiguration is initialized.

**Exception:** 

System.TypeInitializationException: The type initializer for 'REMT.Telemetry.TelemetryHelper' threw an exception.
[2021-10-07T08:32:56.683Z]  ---> System.TypeInitializationException: The type initializer for 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' threw an exception.
[2021-10-07T08:32:56.683Z]  ---> System.NullReferenceException: Object reference not set to an instance of an object.
[2021-10-07T08:32:56.683Z]    at System.Diagnostics.Tracing.CounterGroup.OnEventSourceCommand(Object sender, EventCommandEventArgs e)
[2021-10-07T08:32:56.683Z]    at System.Diagnostics.Tracing.EventSource.add_EventCommandExecuted(EventHandler`1 value)
[2021-10-07T08:32:56.683Z]    at System.Diagnostics.Tracing.CounterGroup.RegisterCommandCallback()
[2021-10-07T08:32:56.683Z]    at System.Diagnostics.Tracing.CounterGroup..ctor(EventSource eventSource)
[2021-10-07T08:32:56.683Z]    at System.Diagnostics.Tracing.CounterGroup.GetCounterGroup(EventSource eventSource)
[2021-10-07T08:32:56.683Z]    at System.Diagnostics.Tracing.DiagnosticCounter.Publish()
[2021-10-07T08:32:56.683Z]    at System.Diagnostics.Tracing.EventCounter..ctor(String name, EventSource eventSource)
[2021-10-07T08:32:56.683Z]    at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource..ctor()
[2021-10-07T08:32:56.683Z]    at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource..cctor()
[2021-10-07T08:32:56.683Z]    --- End of inner exception stack trace ---
[2021-10-07T08:32:56.683Z]    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.SelectInstrumentationKey(TelemetryConfiguration configuration)
[2021-10-07T08:32:56.683Z]    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules, String serializedConfiguration)
[2021-10-07T08:32:56.683Z]    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules)
[2021-10-07T08:32:56.683Z]    at **Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.CreateDefault()**
[2021-10-07T08:32:56.683Z]    at Test.Telemetry.TelemetryHelper..cctor()
[2021-10-07T08:32:56.683Z] --- End of stack trace from previous location ---
[2021-10-07T08:32:56.683Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2021-10-07T08:32:56.683Z]    --- End of inner exception stack trace ---
[2021-10-07T08:32:56.683Z]    at Test.Telemetry.TelemetryHelper.WriteMessage(String message, SeverityLevel severity, VerbosityLevel verbosityLevel)

**Functions Runtime:** 

Azure Functions Core Tools
Core Tools Version:       4.0.3780 Commit hash: 2b9e0e618f69993ff119009e48587b67ac85450e  (64-bit)
Function Runtime Version: 4.0.0.16394

**Comment by TimothyMothra** [comment]
Just curious, what MacOS are you using? Are you using an Intel-based or M1 (ARM) ?

Our [CoreEventSource](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/CoreEventSource.cs#L13) class uses [System.Diagnostics.Tracing.EventSource](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=net-5.0#remarks).
I believe this is platform-independent and I haven't seen reports of conflicts with MacOS.

--
To help verify, I set up a new repo with a unit test to call `CreateDefault()`:
https://github.com/TimothyMothra/InspectApplicationInsights/blob/cc93e0d57c97e6389bdcc3a1d119b13780389138/TestProject1/UnitTest1.cs#L8-L16

I've got this running on 3 platforms:
https://github.com/TimothyMothra/InspectApplicationInsights/blob/cc93e0d57c97e6389bdcc3a1d119b13780389138/.github/workflows/build-and-test.yml#L21

And this test is passing without errors:
https://github.com/TimothyMothra/InspectApplicationInsights/actions/runs/1317403129

**Comment by sergeysolod17** [comment]
@TimothyMothra Thank you! I run your test on my Macbook and all is Ok. 

After investigation, I found that the problem was in the built-in AppInsights in the Azure Functions - I renamed the settings for it("APPINSIGHTS_INSTRUMENTATIONKEY") and everything started working.

 I am using MacOS Big Sur 11.2.3 (20D91) on MacBook Pro (Mid 2014)  with Intel Core i7.
