### ISSUE TITLE
Error on handling AddSingletonIfNotExists (AddApplicationInsightsTelemetryWorkerService)

### ISSUE THREAD

**Issue by JJong-nl** [microsoft/ApplicationInsights-dotnet#2921]
I have a service on the `ServiceCollection` that has no `ImplementationType` and no `ImplementationInstance`.
It is a **`KeyedImplementationType`**

https://github.com/microsoft/ApplicationInsights-dotnet/blob/e34286b4c8175d7ea47f9227c5b981d661cac470/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L293-L301

Than the `ImplementationInstance.GetType()` returns an error.
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

The problem is that the DiagnosticsTelemetryModule is not registred to the ServiceProvider.

repro ..
use **Scrutor >=5.0.2** for adding decorators
add services
add  decorators for specific open generic interfaces. cq `services.Decorate(typeof(IMessageHandler<>), typeof({yourdecoratortype<>}));`
```
services.AddHostedService<ChannelWorker>();
services.AddApplicationInsightsTelemetryWorkerService();
if (services.Where(o=>o.ImplementationType == typeof(DiagnosticsTelemetryModule)).Count() == 0)
{
    throw new Exception("There is no DiagnosticsTelemetryModule registred.");
}
```

**Comment by JJong-nl** [comment]
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Scrutor" Version="5.0.2" />

```
using Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing;
using Test;

var builder = Host.CreateApplicationBuilder(args);

builder.Services.AddServices(builder.Configuration);

var host = builder.Build();
host.Run();


namespace Test
{
    public static class Module
    {
        internal static IServiceCollection AddServices(this IServiceCollection services, IConfiguration configuration)
        {
            // <-- Here we can use AddApplicationInsightsTelemetryWorkerService()

            // register all handlers
            services.Scan(scan =>
                scan.FromAssemblies(typeof(Module).Assembly)
                .AddClasses(classes => classes.AssignableTo(typeof(IMessageHandler<>)).Where(t => !t.IsGenericType))
                .AsImplementedInterfaces(t => t.GetGenericTypeDefinition() == typeof(IMessageHandler<>))
                .WithTransientLifetime());

            // <-- Here we can use AddApplicationInsightsTelemetryWorkerService()

            services.Decorate(typeof(IMessageHandler<>), typeof(MessageHandlerDecorator<>));

            // <-- Here we can NOT use AddApplicationInsightsTelemetryWorkerService()
            services.AddApplicationInsightsTelemetryWorkerService();

            if (services.Where(o => !o.IsKeyedService && o.ImplementationType == typeof(DiagnosticsTelemetryModule)).Count() == 0)
            {
                throw new Exception("There is no DiagnosticsTelemetryModule registred.");
            }

            services.AddHostedService<Worker>();
            return services;
        }
    }

    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        public Worker(ILogger<Worker> logger)
        {
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                // ..
                // handling messages
                _logger.LogInformation("Starting succes");
                await Task.Delay(1000, stoppingToken);
            }
        }
    }

    public interface IMessageHandler<T> where T : BaseMessage
    {
        Task HandleAsync(T message, CancellationToken cancellationToken);
    }

    public class BaseMessage
    {
        public string Value { get; set; } = "";
    }

    public class MessageHandler : IMessageHandler<BaseMessage>
    {
        private readonly ILogger<MessageHandler> _logger;
        private readonly IConfiguration _configuration;

        public MessageHandler(ILogger<MessageHandler> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        public async Task HandleAsync(BaseMessage message, CancellationToken cancellationToken)
        {
            _logger.LogInformation($"Handling: {message.Value}");

        }
    }

    public class MessageHandlerDecorator<T> : IMessageHandler<T>
        where T : BaseMessage
    {
        IMessageHandler<T> _handler;

        public MessageHandlerDecorator(IMessageHandler<T> handler)
        {
            _handler = handler;
        }

        public async Task HandleAsync(T message, CancellationToken cancellationToken)
        {
            // do some stuff for decorating..
            await _handler.HandleAsync(message, cancellationToken);
        }
    }
}
```

**Comment by johanbenschop** [comment]
We encountered this issue after upgrading to .NET 9, along with many other NuGet packages. At first, we got an error saying the instrumentation key was invalid, but after debugging and noticing the IDE breaking in the call to `AddSingletonIfNotExists`  for the null reference exception mentioned and seeing down the stack in `AddApplicationInsightsTelemetry()` the try/catch, we figured this error was due to the incomplete services registration. 

The solution was to place the `services.AddApplicationInsights();` call to the top so the bug has no chance of bugging.

```
fail: Microsoft.ApplicationInsights.Profiler.Core.IServiceProfilerContext[0]
      Profiler Instrumentation Key is invalid.
      Microsoft.ServiceProfiler.Agent.Exceptions.InstrumentationKeyInvalidException: Instrumentation Key is empty.
         at Microsoft.ServiceProfiler.Utilities.AppInsightsProfileFetcher.FetchProfileAsync(Guid iKey, Uri endpoint, Int32 retryCount, Action`1 responseCallback)
         at Microsoft.ApplicationInsights.Profiler.Core.ServiceProfilerContext.GetAppInsightsAppIdAsync()
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' while attempting to activate 'Microsoft.ApplicationInsights.Profiler.Core.Auth.AuthTokenProvider'.
```

This is related to #2915.

**Comment by claudiogodoy99** [comment]
It has been solved on the PR: microsoft/ApplicationInsights#2908

**Comment by zhimin-z** [comment]
This issue is stale because it has been open 300 days with no activity. Remove stale label or this will be closed in 7 days. Commenting will instruct the bot to automatically remove the label.
