### ISSUE TITLE
TelemetryClient.Initialize should not crash in partial trust scenario

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#416]
Reported here: https://github.com/Microsoft/ApplicationInsights-Home/issues/87

`TelemetryClient` and other components should not crash when app is running in partial trust

`System.Security.SecurityException
 at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark&amp; stackMark, Boolean isPermSet)
 at System.Security.CodeAccessPermission.Demand()
 at System.Environment.GetEnvironmentVariables()
 at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformImplementation..ctor()
 at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformSingleton.get_Current()
 at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)
 at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
 at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(TraceTelemetry telemetry)
 at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(String message)`

**Comment by dnduffy** [comment]
PR https://github.com/Microsoft/ApplicationInsights-dotnet/pull/420

**Comment by dberryalliance** [comment]
@dnduffy The constructor for `TransmissionProcessor` calls into the `PlatformSingleton` to asses debugging status.  This also breaks in PartialTrust mode.

**Comment by fedejousset** [comment]
I'm still getting an error trying to use TelemetryClient in partial trust mode:

System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

> at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark&amp; stackMark, Boolean isPermSet)
> at System.Security.CodeAccessPermission.Demand()
> at System.AppDomainSetup.VerifyDir(String dir, Boolean normalize)
> at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformImplementation.ReadConfigurationXml()
> at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules)
> at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.get_Active()
> at Microsoft.ApplicationInsights.TelemetryClient..ctor()
> at AppInsights.Plugin.ExamplePlugin.Execute(IServiceProvider serviceProvider)
> at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.&lt;&gt;c__DisplayClass8.&lt;Execute&gt;b__1()

Should I create another isssue or is it part of this one? @SergeyKanzhelev / @dnduffy 

Thank you!

**Comment by SergeyKanzhelev** [comment]
Reopened an issue

**Comment by cijothomas** [comment]
Fixed in #1119
