### ISSUE TITLE
Nullref after upgrading to 2.5

### ISSUE THREAD

**Issue by andrasg** [Microsoft/ApplicationInsights-dotnet#707]
Since upgrading to version 2.5 of the SDK I am receiving a `System.NullReferenceException` when sending certain telemetry.

## Repro Steps
1. run the following code:
```
var properties = new Dictionary<string, string>
{
   { TelemetryPropertyNames.CorrelationId, mockContext.CorrelationId.ToString() }
};
Tc.TrackTrace($"Request: {request}", properties);
```

(`TelemetryPropertyNames.CorrelationId` is a string constant that has a non-null value)

##  Actual Behavior

Receiving the following exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ApplicationInsights.Shared.Extensibility.Implementation.PassThroughProcessor.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor.Process(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
   at My.Namespace.ActivityLogInspector.AfterReceiveRequest(Message& request, IClientChannel channel, InstanceContext instanceContext)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.AfterReceiveRequestCore(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(B...).
```

## Expected Behavior

No exception encountered.

## Version Info 
SDK Version : 2.5
.NET Version :	4.6.2 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS2017
OS : Win10
Hosting Info (IIS/Azure WebApps/ etc) : IIS

**Comment by MS-TimothyMothra** [comment]
Hi @andrasg, I'm trying to investigate your issue. I have a few questions;

You said this occurs when you send certain telemetry, is this error dependably a specific telemetry type?
Is your application by any chance in the process of shutting down when this occurs?

If you can reproduce this and share in a simple app, that would be very helpful.

**Comment by andrasg** [comment]
Hi, it turns out I was making a mistake by registering AppInsights components (dependencycollector and telemetryclient) as transient instead of singletons. Going to singletons made the issue disappear.

**Comment by MS-TimothyMothra** [comment]
@andrasg We're happy to hear you were able to resolve your issue.
If you have the time, we would appreciate it if you could share a small repo project of how you got this exception. It's an unexpected scenario that we would like to investigate.
