### ISSUE TITLE
MetricManager.Flush is tracking events on a partially disposed TelemetryConfiguration when called from  AutocollectedMetricsExtractor.Dispose()

### ISSUE THREAD

**Issue by clguiman** [microsoft/ApplicationInsights-dotnet#901]
AutocollectedMetricsExtractor.Dispose() calls metricsClient.Flush() which in turns calls TrackMetricAggregates that might call TelemetryClient.Track on the same TelemetryConfiguration that is getting disposed.

For example in this callstack SnapshotCollectorTelemetryProcessor.Disposed was called:
`Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.Dispose()
Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose(Boolean disposing) 
 Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Dispose(Boolean disposing)
Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Dispose()
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.Dispose()
Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()`

Then MetricManager gets disposed and triggers an exception in SnapshotCollectorTelemetryProcessor because it doesn't expect to be called again after being disposed:

`System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.get_Token()
at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.IsProcessorEnabled(ITelemetry item)
at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.Process(ITelemetry item)
at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
at Microsoft.ApplicationInsights.Metrics.Extensibility.ApplicationInsightsTelemetryPipeline.TrackAsync(MetricAggregate metricAggregate, CancellationToken cancelToken)
at Microsoft.ApplicationInsights.Metrics.MetricManager.TrackMetricAggregates(AggregationPeriodSummary aggregates, Boolean flush)
at Microsoft.ApplicationInsights.Metrics.MetricManager.Flush(Boolean flushDownstreamPipeline)
at Microsoft.ApplicationInsights.TelemetryClient.Flush()
at Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor.Dispose()
at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose(Boolean disposing)
at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Dispose(Boolean disposing)
at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Dispose()
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.Dispose()
at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()`

## Version Info 
SDK Version : 2.7.2
.NET Version :	netcore 2.1 (Microsoft.ApplicationInsights.AspNetCore 2.4.1)

**Comment by Dmitry-Matveev** [comment]
@macrogreg, can you please take a look at this issue?
